/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.itson.restaurante.utilerias;

import org.itson.restaurante.presentacion.Controlador;

/**
 *
 * @author joset
 */
public class PanelHeader extends javax.swing.JPanel {
    private Controlador controlador = Controlador.getIntancia();
    
    /**
     * Creates new form PanelHeader
     */
    public PanelHeader() {
        initComponents();
        utilerias.colocarLogo(btnLogo);
        configurarSegunRol();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panSuperior = new javax.swing.JPanel();
        btnLogo = new javax.swing.JButton();
        lblNombreRestaurante = new javax.swing.JLabel();

        panSuperior.setBackground(new java.awt.Color(18, 44, 79));
        panSuperior.setLayout(new javax.swing.BoxLayout(panSuperior, javax.swing.BoxLayout.LINE_AXIS));

        btnLogo.setText("btnLogo");
        btnLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoActionPerformed(evt);
            }
        });
        panSuperior.add(btnLogo);

        lblNombreRestaurante.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombreRestaurante.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreRestaurante.setText("Nombre del restaurante");
        panSuperior.add(lblNombreRestaurante);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public void configurarSegunRol() {
        if (Controlador.getIntancia().esMesero() || Controlador.getIntancia().noRol() ) {
            btnLogo.setEnabled(false);
        }
    }
    private void btnLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoActionPerformed
       controlador.abrirMenuPrincipal(
                (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this)
        );
    }//GEN-LAST:event_btnLogoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogo;
    private javax.swing.JLabel lblNombreRestaurante;
    private javax.swing.JPanel panSuperior;
    // End of variables declaration//GEN-END:variables
}
