/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.restaurante.presentacion;

import org.itson.restaurante.dtos.ClienteFrecuenteDTO;
import org.itson.restaurante.dtos.NuevoClienteFrecuenteDTO;
import org.itson.restaurante.utilerias.utilerias;
import org.itson.restaurante.negocio.NegocioException;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import org.itson.restaurante.dtos.IngredienteDTO;
import org.itson.restaurante.utilerias.PanelHeader;
import org.itson.restaurante.utilerias.PanelNavegacionPantallasPrincipales;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author joset
 */
public class PantallaFormularioIngrediente extends javax.swing.JFrame {

    private IngredienteDTO ingredienteForm = null;

    /**
     * Creates new form PantallaFormularioCliente
     */
    public PantallaFormularioIngrediente() {
        initComponents();
        
        panelHeader = new PanelHeader();
        panelNavegacion = new PanelNavegacionPantallasPrincipales();
        
        panPrincipal.add(panelHeader, new AbsoluteConstraints(0, 0, 1366, 130));       
        panPrincipal.add(panelNavegacion, new AbsoluteConstraints(0, 130, 1366, 45));
        
        panelNavegacion.setPantallasNavegacion("Ingredientes", "Formulario");
        
        utilerias.estilizarBotonPrimario(btnEditarIngrediente);

        utilerias.estilizarBotonPrimario(btnGuardarIngrediente);
        
        utilerias.estilizarBotonSinFondo(btnCancelar);

        btnGuardarIngrediente.setVisible(true);
        btnEditarIngrediente.setVisible(false);
        

        this.setLocationRelativeTo(null);

    }

    public PantallaFormularioIngrediente(IngredienteDTO ingrediente) {
        initComponents();
        
        panelHeader = new PanelHeader();
        panelNavegacion = new PanelNavegacionPantallasPrincipales();
        
        panPrincipal.add(panelHeader, new AbsoluteConstraints(0, 0, 1366, 130));       
        panPrincipal.add(panelNavegacion, new AbsoluteConstraints(0, 130, 1366, 45));
        
        panelNavegacion.setPantallasNavegacion("Clientes Frecuentes", "Formulario");
        
        utilerias.estilizarBotonPrimario(btnEditarIngrediente);

        utilerias.estilizarBotonPrimario(btnGuardarIngrediente);

        utilerias.estilizarBotonSinFondo(btnCancelar);
        
        btnGuardarIngrediente.setVisible(false);
        btnEditarIngrediente.setVisible(true);

        this.setLocationRelativeTo(null);

        this.ingredienteForm = ingrediente;
        
        llenarCampos(this.ingredienteForm);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        lblPantalla = new javax.swing.JLabel();
        sep = new javax.swing.JSeparator();
        btnCancelar = new javax.swing.JButton();
        btnGuardarIngrediente = new javax.swing.JButton();
        txtApellidoP = new javax.swing.JTextField();
        lblApellidoPaterno = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtCorreoElectronico = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        lblApellidoMaterno = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JTextField();
        lblTelefonod = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnEditarIngrediente = new javax.swing.JButton();
        panContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario Cliente");
        setSize(new java.awt.Dimension(1366, 768));

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panPrincipal.setMaximumSize(new java.awt.Dimension(1366, 768));
        panPrincipal.setPreferredSize(new java.awt.Dimension(1366, 768));
        panPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPantalla.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        lblPantalla.setText("Formulario Ingrediente");
        panPrincipal.add(lblPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        sep.setForeground(new java.awt.Color(18, 44, 79));
        panPrincipal.add(sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 1060, 10));

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(18, 44, 79));
        btnCancelar.setText("Cancelar ");
        btnCancelar.setOpaque(true);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panPrincipal.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 550, 190, 30));

        btnGuardarIngrediente.setBackground(new java.awt.Color(18, 44, 79));
        btnGuardarIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnGuardarIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarIngrediente.setText("Guardar Ingrediente");
        btnGuardarIngrediente.setToolTipText("");
        btnGuardarIngrediente.setMaximumSize(new java.awt.Dimension(149, 32));
        btnGuardarIngrediente.setMinimumSize(new java.awt.Dimension(149, 32));
        btnGuardarIngrediente.setPreferredSize(new java.awt.Dimension(149, 32));
        btnGuardarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarIngredienteActionPerformed(evt);
            }
        });
        panPrincipal.add(btnGuardarIngrediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 550, 190, 30));
        panPrincipal.add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, 300, 30));

        lblApellidoPaterno.setText("Apellido Paterno *");
        panPrincipal.add(lblApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, -1, -1));

        lblNombres.setText("Nombres  *");
        panPrincipal.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        panPrincipal.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 300, 30));
        panPrincipal.add(txtCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 300, 30));

        lblCorreo.setText("Correo electronico (opcional)");
        panPrincipal.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, -1, -1));

        lblApellidoMaterno.setText("Apellido Materno *");
        panPrincipal.add(lblApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        txtApellidoMaterno.setToolTipText("");
        panPrincipal.add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 300, 30));

        lblTelefonod.setText("Teléfono *");
        panPrincipal.add(lblTelefonod, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, -1, -1));
        panPrincipal.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, 300, 30));

        btnEditarIngrediente.setBackground(new java.awt.Color(18, 44, 79));
        btnEditarIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnEditarIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarIngrediente.setText("Editar Ingrediente");
        btnEditarIngrediente.setToolTipText("");
        btnEditarIngrediente.setMaximumSize(new java.awt.Dimension(133, 32));
        btnEditarIngrediente.setMinimumSize(new java.awt.Dimension(133, 32));
        btnEditarIngrediente.setPreferredSize(new java.awt.Dimension(133, 32));
        btnEditarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarIngredienteActionPerformed(evt);
            }
        });
        panPrincipal.add(btnEditarIngrediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 550, 190, 30));

        panContenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panContenidoLayout = new javax.swing.GroupLayout(panContenido);
        panContenido.setLayout(panContenidoLayout);
        panContenidoLayout.setHorizontalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        panContenidoLayout.setVerticalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        panPrincipal.add(panContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 177, 1370, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        ingredienteForm = null;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarIngredienteActionPerformed
//        String nombre = txtNombres.getText().trim();
//
//        String apellidoP = txtApellidoP.getText().trim();
//
//        String apellidoM = txtApellidoMaterno.getText().trim();
//
//        String telefono = txtTelefono.getText().trim();
//
//        String correo = txtCorreoElectronico.getText().trim();
//
//        // validacion de los campos vacios
//        if (nombre.isEmpty() || apellidoP.isEmpty() || apellidoM.isEmpty() || telefono.isEmpty()) {
//
//            JOptionPane.showMessageDialog(this,
//                    "Ningún campo puede estar vacío",
//                    "Error",
//                    JOptionPane.ERROR_MESSAGE);
//            return;
//
//        }
//        try {
//            NuevoClienteFrecuenteDTO nuevoCliente = new NuevoClienteFrecuenteDTO(
//                    nombre, apellidoP, apellidoM, telefono, correo, LocalDate.now()
//            );
//
//            Controlador.getIntancia().registrarClienteC(nuevoCliente);
//
//            JOptionPane.showMessageDialog(this,
//                    "Cliente guardado correctamente",
//                    "Éxito",
//                    JOptionPane.INFORMATION_MESSAGE);
//
//            this.dispose(); // se cierra esta y lanza el windowClosed
//        } catch (NegocioException ex) {
//            JOptionPane.showMessageDialog(this,
//                    ex.getMessage(), 
//                    "Aviso", 
//                    JOptionPane.WARNING_MESSAGE);
//        }
    }//GEN-LAST:event_btnGuardarIngredienteActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void btnEditarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarIngredienteActionPerformed
//        String nombre = txtNombres.getText().trim();
//
//        String apellidoP = txtApellidoP.getText().trim();
//
//        String apellidoM = txtApellidoMaterno.getText().trim();
//
//        String telefono = txtTelefono.getText().trim();
//
//        String correo = txtCorreoElectronico.getText().trim();
//
//        LocalDate fechaRegistro = ingredienteForm.getFechaRegistro();
//
//        // validacion de los campos vacios
//        if (nombre.isEmpty() || apellidoP.isEmpty() || apellidoM.isEmpty() || telefono.isEmpty()) {
//            JOptionPane.showMessageDialog(this,
//                    "Ningún campo puede estar vacío",
//                    "Error",
//                    JOptionPane.ERROR_MESSAGE);
//            return;
//        }
//        ClienteFrecuenteDTO clienteActualizado = new ClienteFrecuenteDTO(
//                ingredienteForm.getId(), nombre, apellidoP, apellidoM, telefono, correo, fechaRegistro, ingredienteForm.getNumeroVisitas(),
//                ingredienteForm.getTotalGastado(), ingredienteForm.getPuntosAcumulados(), ingredienteForm.getFechaUltimaComanda()
//        );
//        try {
//            Controlador.getIntancia().actualizarClienteC(clienteActualizado);
//
//            this.ingredienteForm = clienteActualizado;
//
//            JOptionPane.showMessageDialog(this,
//                    "Cliente actualizado correctamente",
//                    "Éxito",
//                    JOptionPane.INFORMATION_MESSAGE);
//
//            this.dispose(); // cierra y lanza el windowClosed
//        } catch (NegocioException ex) {
//            JOptionPane.showMessageDialog(this,
//                    ex.getMessage(), 
//                    "Aviso", 
//                    JOptionPane.WARNING_MESSAGE);
//        }
    }//GEN-LAST:event_btnEditarIngredienteActionPerformed

    public IngredienteDTO getIngredienteDTO() {
        return ingredienteForm;
    }

    private void llenarCampos(IngredienteDTO ingrediente) {
//
//        txtNombres.setText(ingrediente.getNombre());
//
//        txtApellidoP.setText(ingrediente.getUnidad());
//
//        txtApellidoMaterno.setText(ingrediente.getStock());
//
//        txtTelefono.setText(ingrediente.getImagen());

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditarIngrediente;
    private javax.swing.JButton btnGuardarIngrediente;
    private javax.swing.JLabel lblApellidoMaterno;
    private javax.swing.JLabel lblApellidoPaterno;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblPantalla;
    private javax.swing.JLabel lblTelefonod;
    private javax.swing.JPanel panContenido;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JSeparator sep;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCorreoElectronico;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
    private org.itson.restaurante.utilerias.PanelHeader panelHeader;
    private org.itson.restaurante.utilerias.PanelNavegacionPantallasPrincipales panelNavegacion;
}
