package org.itson.restaurante.presentacion;

import org.itson.restaurante.controladores.Controlador;
import javax.swing.JOptionPane;
import org.itson.restaurante.utilerias.utilerias;
import javax.swing.SwingUtilities;
import org.itson.restaurante.controladores.ControladorIngrediente;
import org.itson.restaurante.dtos.IngredienteDTO;
import org.itson.restaurante.negocio.NegocioException;
import org.itson.restaurante.utilerias.PanelHeader;
import org.itson.restaurante.utilerias.PanelMenu;
import org.itson.restaurante.utilerias.PanelNavegacionPantallasPrincipales;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author joset
 */
public class PantallaIngredientes extends javax.swing.JFrame {
     private ControladorIngrediente control;
    /**
     * Creates new form PantallaCliente
     */
    public PantallaIngredientes() {
        initComponents();
        utilerias.aplicarIcono(this);
        //paneles reutilizables
        panelHeader = new PanelHeader();
        panelMenu = new PanelMenu();
        panelNavegacion = new PanelNavegacionPantallasPrincipales();

        panPrincipal.add(panelHeader, new AbsoluteConstraints(0, 0, 1366, 130));
        panPrincipal.add(panelMenu, new AbsoluteConstraints(0, 130, 215, 640));
        panPrincipal.add(panelNavegacion, new AbsoluteConstraints(215, 130, 1151, 45));

        panelNavegacion.setPantallasNavegacion("Ingredientes", "Menu Ingredientes");

        utilerias.estilizarBotonPrimario(btnEditarIngrediente);

        utilerias.estilizarBotonPrimario(btnNuevoIngrediente);
        
        utilerias.estilizarBotonSinFondo(btnEliminarIngrediente);

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        lblPrincipal1 = new javax.swing.JLabel();
        sep = new javax.swing.JSeparator();
        panContenido = new javax.swing.JPanel();
        btnEliminarIngrediente = new javax.swing.JButton();
        btnNuevoIngrediente = new javax.swing.JButton();
        btnEditarIngrediente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Ingredientes");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panPrincipal.setMaximumSize(new java.awt.Dimension(1366, 768));
        panPrincipal.setPreferredSize(new java.awt.Dimension(1366, 768));
        panPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPrincipal1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        lblPrincipal1.setText("Menu Ingredientes");
        panPrincipal.add(lblPrincipal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        sep.setForeground(new java.awt.Color(18, 44, 79));
        panPrincipal.add(sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 1080, -1));

        panContenido.setBackground(new java.awt.Color(255, 255, 255));

        btnEliminarIngrediente.setBackground(new java.awt.Color(18, 44, 79));
        btnEliminarIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEliminarIngrediente.setText("Eliminar Ingrediente");
        btnEliminarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarIngredienteActionPerformed(evt);
            }
        });

        btnNuevoIngrediente.setBackground(new java.awt.Color(18, 44, 79));
        btnNuevoIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNuevoIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoIngrediente.setText("Nuevo Ingrediente");
        btnNuevoIngrediente.setToolTipText("");
        btnNuevoIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoIngredienteActionPerformed(evt);
            }
        });

        btnEditarIngrediente.setBackground(new java.awt.Color(18, 44, 79));
        btnEditarIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditarIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarIngrediente.setText("Editar Ingrediente");
        btnEditarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarIngredienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panContenidoLayout = new javax.swing.GroupLayout(panContenido);
        panContenido.setLayout(panContenidoLayout);
        panContenidoLayout.setHorizontalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panContenidoLayout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(btnNuevoIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(btnEditarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(btnEliminarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
        panContenidoLayout.setVerticalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panContenidoLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoIngrediente)
                    .addComponent(btnEditarIngrediente)
                    .addComponent(btnEliminarIngrediente))
                .addContainerGap(465, Short.MAX_VALUE))
        );

        panPrincipal.add(panContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 1150, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoIngredienteActionPerformed

        Controlador.getIntancia().abrirFomularioIngrediente(this);
    }//GEN-LAST:event_btnNuevoIngredienteActionPerformed

    private void btnEditarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarIngredienteActionPerformed
        PantallaBusquedaIngrediente dialogo = new PantallaBusquedaIngrediente((java.awt.Frame) SwingUtilities.getWindowAncestor(this), true);
        dialogo.setVisible(true);

        IngredienteDTO ingrediente = dialogo.getIngredienteSeleccionado();

        if (ingrediente != null) {
            control.abrirFormularioEditarIngrediente(ingrediente, this);
        }
    }//GEN-LAST:event_btnEditarIngredienteActionPerformed

    private void btnEliminarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarIngredienteActionPerformed
        PantallaBusquedaIngrediente dialogo = new PantallaBusquedaIngrediente((java.awt.Frame) SwingUtilities.getWindowAncestor(this), true);
        dialogo.setVisible(true);

        IngredienteDTO ingrediente = dialogo.getIngredienteSeleccionado();

        if (ingrediente != null) {
            try {
               IngredienteDTO ingredienteEliminado = control.eliminarIngrediente(ingrediente);
                JOptionPane.showMessageDialog(this,"Se elimino el ingrediente: "+ ingredienteEliminado.getNombre(),"Ingrediente Eliminado",JOptionPane.INFORMATION_MESSAGE);
            } catch (NegocioException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarIngredienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarIngrediente;
    private javax.swing.JButton btnEliminarIngrediente;
    private javax.swing.JButton btnNuevoIngrediente;
    private javax.swing.JLabel lblPrincipal1;
    private javax.swing.JPanel panContenido;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JSeparator sep;
    // End of variables declaration//GEN-END:variables
    private org.itson.restaurante.utilerias.PanelHeader panelHeader;
    private org.itson.restaurante.utilerias.PanelMenu panelMenu;
    private org.itson.restaurante.utilerias.PanelNavegacionPantallasPrincipales panelNavegacion;
}
