/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.restaurante.presentacion;

import java.awt.Color;
import static java.awt.SystemColor.control;
import java.awt.event.KeyEvent;
import java.io.File;
import java.time.LocalDate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.itson.restaurante.dtos.ClienteFrecuenteDTO;
import org.itson.restaurante.dtos.ComandaDTO;
import org.itson.restaurante.negocio.ClienteFrecuenteBO;
import org.itson.restaurante.negocio.ComandaBO;
import org.itson.restaurante.negocio.IClienteFrecuenteBO;
import org.itson.restaurante.negocio.IComandaBO;
import org.itson.restaurante.negocio.NegocioException;
import org.itson.restaurante.negocio.ReporteBO;
import org.itson.restaurante.utilerias.PanelHeader;
import org.itson.restaurante.utilerias.PanelMenu;
import org.itson.restaurante.utilerias.PanelNavegacionPantallasPrincipales;
import org.itson.restaurante.utilerias.utilerias;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author joset
 */
public class PantallaReportesCliente extends javax.swing.JFrame {

    private List<ClienteFrecuenteDTO> listaClientes;
    private IClienteFrecuenteBO clienteBO = new ClienteFrecuenteBO();
    

    /**
     * Creates new form PantallaReportes
     */
    public PantallaReportesCliente() {
        initComponents();
        this.revalidate();
        this.repaint();
        setLocationRelativeTo(null);
        configurarTabla();


        panPrinciapl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());


        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader = new PanelHeader();
        panelMenu = new PanelMenu();

        jPanel1.add(panelHeader, new AbsoluteConstraints(0, 0, 1366, 130));
        jPanel1.add(panelMenu, new AbsoluteConstraints(0, 130, 215, 640));

        jPanel1.add(panPrinciapl, new AbsoluteConstraints(215, 130, 1151, 638));

        jPanel1.setComponentZOrder(panelMenu, 0);
        jPanel1.setComponentZOrder(panPrinciapl, 1);

        

        try {
            listaClientes = clienteBO.consultarClientes();
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error "+ex.getMessage());
        }
        cargarClientes(listaClientes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panPrinciapl = new javax.swing.JPanel();
        btnGuardarPDF = new javax.swing.JButton();
        btnConsultarPDf = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIngredientes = new javax.swing.JTable();
        sep = new javax.swing.JSeparator();
        lblPantalla = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));

        panPrinciapl.setBackground(new java.awt.Color(255, 255, 255));
        panPrinciapl.setMaximumSize(new java.awt.Dimension(1366, 768));
        panPrinciapl.setMinimumSize(new java.awt.Dimension(1366, 768));
        panPrinciapl.setPreferredSize(new java.awt.Dimension(1366, 768));
        panPrinciapl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardarPDF.setBackground(new java.awt.Color(18, 44, 79));
        btnGuardarPDF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGuardarPDF.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarPDF.setText("Guardar en PDF");
        btnGuardarPDF.setToolTipText("");
        btnGuardarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPDFActionPerformed(evt);
            }
        });
        panPrinciapl.add(btnGuardarPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(919, 529, 240, -1));

        btnConsultarPDf.setBackground(new java.awt.Color(18, 44, 79));
        btnConsultarPDf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnConsultarPDf.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarPDf.setText("Consultar Detalles");
        btnConsultarPDf.setToolTipText("");
        btnConsultarPDf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPDfActionPerformed(evt);
            }
        });
        panPrinciapl.add(btnConsultarPDf, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, 240, -1));

        tblIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblIngredientes.setFillsViewportHeight(true);
        tblIngredientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblIngredientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblIngredientes);

        panPrinciapl.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 1060, 350));

        sep.setForeground(new java.awt.Color(18, 44, 79));
        panPrinciapl.add(sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 1060, 10));

        lblPantalla.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        lblPantalla.setText("Reporte comandas");
        panPrinciapl.add(lblPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        txtBuscar.setText("Ingresa el nombre");
        panPrinciapl.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 770, -1));

        btnBuscar.setBackground(new java.awt.Color(18, 44, 79));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panPrinciapl.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 90, 240, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 158, Short.MAX_VALUE)
                .addComponent(panPrinciapl, javax.swing.GroupLayout.PREFERRED_SIZE, 1208, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(panPrinciapl, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void configurarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[]{"Nombre", "Numero de visitas", "Total gastado", "Fecha ultima comanda"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblIngredientes.setModel(modelo); // Aunque se llame tblIngredientes, la usaremos para clientes
    }

    private void cargarClientes(List<ClienteFrecuenteDTO> lista) {
        DefaultTableModel modelo = (DefaultTableModel) tblIngredientes.getModel();
        modelo.setRowCount(0);
        for (ClienteFrecuenteDTO c : lista) {
            modelo.addRow(new Object[]{
                c.getNombre().concat(" " + c.getApellidoPaterno()),
                c.getNumeroVisitas(),
                c.getTotalGastado(),
                c.getFechaUltimaComanda()
            });
        }
    }
    private void btnGuardarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPDFActionPerformed
        try {
        
        ReporteBO bo = new ReporteBO();
        JasperPrint jp = bo.generarReporteCliente(this.txtBuscar.getText());

        if (jp == null || jp.getPages().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El reporte no contiene datos para el nombre seleccionadas.", "Reporte Vacío", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setSelectedFile(new File("ReporteClientes.pdf"));

        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            String ruta = fileChooser.getSelectedFile().getAbsolutePath();

            if (!ruta.toLowerCase().endsWith(".pdf")) {
                ruta += ".pdf";
            }

            JasperExportManager.exportReportToPdfFile(jp, ruta);
            JOptionPane.showMessageDialog(this, "PDF generado correctamente en:\n" + ruta);
        }

    } catch (net.sf.jasperreports.engine.JRRuntimeException ex) {
        String mensaje = "Error al intentar guardar el archivo:\n";
        if (ex.getMessage().contains("Acceso denegado")) {
            mensaje += "- No tienes permisos para escribir en esta carpeta.\n- O el archivo ya está abierto por otro programa.";
        } else {
            mensaje += "- Verifica que la ruta seleccionada sea válida.";
        }
        JOptionPane.showMessageDialog(this, mensaje, "Error de Archivo", JOptionPane.ERROR_MESSAGE);

        
    } catch (NegocioException | JRException ex) {
        JOptionPane.showMessageDialog(this, "Error de lógica o reporte: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + ex.getMessage(), "Error Crítico", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnGuardarPDFActionPerformed

    private void btnConsultarPDfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPDfActionPerformed
         try {
               ReporteBO bo = new ReporteBO();

               JasperPrint jp = bo.generarReporteCliente(this.txtBuscar.getText());

               if (jp != null) {
                   JasperViewer.viewReport(jp, false);
               }

           } catch (Exception ex) {
               JOptionPane.showMessageDialog(this, ex.getMessage());
           }
    }//GEN-LAST:event_btnConsultarPDfActionPerformed
    private void actualizarTablaPorFechas() {

        try {
            listaClientes = clienteBO.consultarClienteFiltro(this.txtBuscar.getText());

            cargarClientes(listaClientes);

            if (listaClientes.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay un nombre ingresado");
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al filtrar: " + ex.getMessage());
        }
    }
    private void tblIngredientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblIngredientesMouseClicked

    }//GEN-LAST:event_tblIngredientesMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaReportesCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaReportesCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaReportesCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaReportesCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaReportesCliente().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnConsultarPDf;
    private javax.swing.JButton btnGuardarPDF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPantalla;
    private javax.swing.JPanel panPrinciapl;
    private javax.swing.JSeparator sep;
    private javax.swing.JTable tblIngredientes;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
    private org.itson.restaurante.utilerias.PanelHeader panelHeader;
    private org.itson.restaurante.utilerias.PanelMenu panelMenu;
    private com.toedter.calendar.JDateChooser fechaInicioChooser;
    private com.toedter.calendar.JDateChooser fechaFinChooser;
}
