
package org.itson.restaurante.presentacion;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import org.itson.restaurante.controladores.ControladorComandas;
import org.itson.restaurante.dtos.MesaDTO;
import org.itson.restaurante.dtos.NuevoProductoComandaDTO;
import org.itson.restaurante.utilerias.PanelHeader;
import org.itson.restaurante.utilerias.PanelNavegacionPantallasPrincipales;
import org.itson.restaurante.utilerias.utilerias;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author oliro
 */
public class PantallaFormularioComanda extends javax.swing.JFrame {
    
    private PanelHeader panelHeader;
    private PanelNavegacionPantallasPrincipales panelNavegacion;
    
    private ControladorComandas control;
    
    /**
     * Creates new form PantallaFormularioComanda
     */
    public PantallaFormularioComanda(ControladorComandas control) {
        
        this.control = control;
        initComponents();
        
        panelHeader = new PanelHeader();
        panelNavegacion = new PanelNavegacionPantallasPrincipales();
        
        panelPrincipal.add(panelHeader, new AbsoluteConstraints(0, 0, 1366, 130));
        panelPrincipal.add(panelNavegacion, new AbsoluteConstraints(0, 130, 1366, 45));
        
        utilerias.estilizarBotonPrimario(btnAgregarProducto);
        utilerias.estilizarBotonPrimario(btnBuscarCliente);
        utilerias.estilizarBotonPrimario(btnRegistrar);
        utilerias.estilizarBotonSinFondo(btnCancelar);
        utilerias.estilizarBotonSinFondo(btnClienteGeneral);
        utilerias.estilizarTabla(tblProductosComandas);
        
        tblProductosComandas.getSelectionModel().addListSelectionListener(e -> {
            if(e.getValueIsAdjusting()) return;
            int fila = tblProductosComandas.getSelectedRow();
            if(fila == -1) {
                btnSumar.setEnabled(false);
                btnRestar.setEnabled(false);
                return;
            }
            btnSumar.setEnabled(true);
            btnRestar.setEnabled(true);
            txtCantidad.setText(tblProductosComandas.getValueAt(fila, 4).toString());
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelContenido = new javax.swing.JPanel();
        lblPrincipal1 = new javax.swing.JLabel();
        sep = new javax.swing.JSeparator();
        btnCancelar = new javax.swing.JButton();
        btnBuscarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductosComandas = new javax.swing.JTable();
        cbxMesa = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnAgregarProducto = new javax.swing.JButton();
        btnClienteGeneral = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btnSumar = new javax.swing.JButton();
        txtCantidad = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setPreferredSize(new java.awt.Dimension(1366, 770));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelContenido.setBackground(new java.awt.Color(255, 255, 255));

        lblPrincipal1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        lblPrincipal1.setText("Comandas");

        sep.setForeground(new java.awt.Color(18, 44, 79));

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setPreferredSize(new java.awt.Dimension(200, 32));
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnBuscarCliente.setBackground(new java.awt.Color(18, 44, 79));
        btnBuscarCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarCliente.setText("Buscar cliente");
        btnBuscarCliente.setPreferredSize(new java.awt.Dimension(200, 32));
        btnBuscarCliente.addActionListener(this::btnBuscarClienteActionPerformed);

        tblProductosComandas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Producto", "Comentario", "Precio unit.", "Cantidad", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProductosComandas);
        if (tblProductosComandas.getColumnModel().getColumnCount() > 0) {
            tblProductosComandas.getColumnModel().getColumn(0).setMinWidth(40);
            tblProductosComandas.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblProductosComandas.getColumnModel().getColumn(0).setMaxWidth(40);
            tblProductosComandas.getColumnModel().getColumn(1).setMinWidth(250);
            tblProductosComandas.getColumnModel().getColumn(1).setPreferredWidth(250);
            tblProductosComandas.getColumnModel().getColumn(1).setMaxWidth(250);
            tblProductosComandas.getColumnModel().getColumn(2).setMinWidth(250);
            tblProductosComandas.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblProductosComandas.getColumnModel().getColumn(2).setMaxWidth(250);
            tblProductosComandas.getColumnModel().getColumn(3).setResizable(false);
            tblProductosComandas.getColumnModel().getColumn(3).setPreferredWidth(50);
            tblProductosComandas.getColumnModel().getColumn(4).setResizable(false);
            tblProductosComandas.getColumnModel().getColumn(4).setPreferredWidth(10);
            tblProductosComandas.getColumnModel().getColumn(5).setResizable(false);
            tblProductosComandas.getColumnModel().getColumn(5).setPreferredWidth(20);
        }

        cbxMesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar mesa" }));
        cbxMesa.setPreferredSize(new java.awt.Dimension(150, 30));

        jLabel1.setText("Numero de Mesa");

        jLabel2.setText("Cliente asociado");

        lblCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCliente.setText("Cliente general");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Productos en la comanda");

        btnRegistrar.setBackground(new java.awt.Color(18, 44, 79));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setPreferredSize(new java.awt.Dimension(200, 32));
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        btnAgregarProducto.setBackground(new java.awt.Color(18, 44, 79));
        btnAgregarProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAgregarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProducto.setText("Agregar producto");
        btnAgregarProducto.setPreferredSize(new java.awt.Dimension(200, 32));
        btnAgregarProducto.addActionListener(this::btnAgregarProductoActionPerformed);

        btnClienteGeneral.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClienteGeneral.setForeground(new java.awt.Color(255, 255, 255));
        btnClienteGeneral.setText("Cliente general");
        btnClienteGeneral.setPreferredSize(new java.awt.Dimension(200, 32));
        btnClienteGeneral.addActionListener(this::btnClienteGeneralActionPerformed);

        btnRestar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRestar.setText("-");
        btnRestar.setEnabled(false);
        btnRestar.addActionListener(this::btnRestarActionPerformed);

        btnSumar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSumar.setText("+");
        btnSumar.setEnabled(false);
        btnSumar.addActionListener(this::btnSumarActionPerformed);

        txtCantidad.setEditable(false);
        txtCantidad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtCantidad.setPreferredSize(new java.awt.Dimension(64, 30));

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotal.setText("0$");
        txtTotal.setActionCommand("<Not Set>");
        txtTotal.setPreferredSize(new java.awt.Dimension(120, 25));

        jLabel5.setText("Total");

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContenidoLayout.createSequentialGroup()
                        .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cbxMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblCliente)))
                    .addComponent(lblPrincipal1)
                    .addComponent(sep, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelContenidoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelContenidoLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelContenidoLayout.createSequentialGroup()
                            .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnClienteGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelContenidoLayout.createSequentialGroup()
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelContenidoLayout.createSequentialGroup()
                            .addComponent(btnRestar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnSumar))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblPrincipal1)
                .addGap(2, 2, 2)
                .addComponent(sep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCliente)
                    .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClienteGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestar)
                    .addComponent(btnSumar)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        panelPrincipal.add(panelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 175, 1370, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(
            this, 
            "Desea descartar la comanda?", 
            "Nueva comanda",
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.WARNING_MESSAGE
        );
        if (respuesta == JOptionPane.YES_OPTION) {
            control.mostarPantallaComandas(this);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        control.seleccionarClienteReferido(this);
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnClienteGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteGeneralActionPerformed
        control.seleccionarClienteGeneral(this);
    }//GEN-LAST:event_btnClienteGeneralActionPerformed

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        int siguienteId = tblProductosComandas.getRowCount() + 1;
        control.agreagarProductoComanda(this, siguienteId);
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        control.registrarComanda(this);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        int fila = tblProductosComandas.getSelectedRow();
        if (fila != -1 ) {
            int idRegistro = Integer.parseInt(tblProductosComandas.getValueAt(fila, 0).toString());
            control.sumarCantidadProducto(this, idRegistro);
            tblProductosComandas.setRowSelectionInterval(fila, fila);
        }
    }//GEN-LAST:event_btnSumarActionPerformed

    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarActionPerformed
        int fila = tblProductosComandas.getSelectedRow();
        if (fila != -1) {
            int idRegistro = Integer.parseInt(tblProductosComandas.getValueAt(fila, 0).toString());
            control.eliminarProducto(this, idRegistro);
            if(tblProductosComandas.getRowCount() > 0) {
                tblProductosComandas.setRowSelectionInterval(fila, fila);
            }
        }
    }//GEN-LAST:event_btnRestarActionPerformed
    
    public void setTextoClienteReferido(String nombreCompleto) {
        lblCliente.setText(nombreCompleto);
    }
    
    public void llenarTabla(List<NuevoProductoComandaDTO> lista) {
        
        DefaultTableModel modelo = (DefaultTableModel) tblProductosComandas.getModel();
        modelo.setRowCount(0); // Limpiamos la tabla
        
        if (lista == null || lista.isEmpty()) {
            return;
        }
        
        Double subtotal = 0d;
        for (NuevoProductoComandaDTO producto : lista) {
            subtotal += producto.getSubtotal();
            Object[] fila = {
                producto.getIdTemporal(),
                producto.getNombreProducto(),
                producto.getDetalles(),
                producto.getPrecioUnitario(),
                producto.getCantidad(),
                producto.getSubtotal()
            };
            modelo.addRow(fila);;
        }
        txtTotal.setText("$" + subtotal);
        
    }
    
    public void llenarCbxMesas(List<MesaDTO> mesas) {
        DefaultComboBoxModel model = new DefaultComboBoxModel<>();
        model.addElement("Seleccionar mesa");
        for (MesaDTO m : mesas) {
            model.addElement(m);
        }
        cbxMesa.setModel(model);
    }
    
    public Object getMesaSeleccionada() {
        return cbxMesa.getSelectedItem();
    }
    
    public void mostarMensaje(String msj, boolean esError) {
        int tipo = esError ? JOptionPane.ERROR_MESSAGE : JOptionPane.INFORMATION_MESSAGE;
        JOptionPane.showMessageDialog(this, msj, "Sistema", tipo);
    }
    
    public boolean mostrarConfirmacionEliminar(String nombreProducto) {
        int respuesta = JOptionPane.showConfirmDialog(
                this, 
                "Desea eliminar " + nombreProducto + " de la comanda?", 
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE
        );
        return respuesta == JOptionPane.YES_OPTION;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnClienteGeneral;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSumar;
    private javax.swing.JComboBox<String> cbxMesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblPrincipal1;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JSeparator sep;
    private javax.swing.JTable tblProductosComandas;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
