/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.restaurante.presentacion;

import org.itson.restaurante.controladores.Controlador;
import org.itson.restaurante.utilerias.PanelHeader;
import org.itson.restaurante.utilerias.PanelMenu;
import org.itson.restaurante.utilerias.PanelNavegacionPantallasPrincipales;
import org.itson.restaurante.utilerias.utilerias;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author joset
 */
public class PantallaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaMenuPrincipal
     */
    public PantallaMenuPrincipal() {
        initComponents();
        utilerias.aplicarIcono(this);
        panelHeader = new PanelHeader();
        panelMenu = new PanelMenu();
        panelNavegacion = new PanelNavegacionPantallasPrincipales();

        panPrincipal.add(panelHeader, new AbsoluteConstraints(0, 0, 1366, 130));
        panPrincipal.add(panelMenu, new AbsoluteConstraints(0, 130, 215, 640));
        panPrincipal.add(panelNavegacion, new AbsoluteConstraints(215, 130, 1151, 45));

        panelNavegacion.setPantallasNavegacion("Inicio", "Resumen del día");
        
       
        // conectar datos al dashboard
        lblNumComandas.setText(
            String.valueOf(Controlador.getIntancia().contarComandasHoy())
        );

        lblCantidadVentas.setText(
            "$" + String.format("%,.2f", Controlador.getIntancia().calcularVentasHoy())
        );

        lblNumMesasOcupadas.setText(
            String.valueOf(Controlador.getIntancia().contarMesasAbiertas())
        );

        lblCantProductosActivos.setText(
            String.valueOf(Controlador.getIntancia().contarProductosActivos())
        );
        this.setLocationRelativeTo(null);
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        lblPrincipal1 = new javax.swing.JLabel();
        sep = new javax.swing.JSeparator();
        panContenido = new javax.swing.JPanel();
        panVentasDiarias = new javax.swing.JPanel();
        lblVentasDiarias = new javax.swing.JLabel();
        lblCantidadVentas = new javax.swing.JLabel();
        panComandasDiarias = new javax.swing.JPanel();
        lblComandasDiarias = new javax.swing.JLabel();
        lblNumComandas = new javax.swing.JLabel();
        PanMesasDisponibles = new javax.swing.JPanel();
        lblMesasAbiertas = new javax.swing.JLabel();
        lblNumMesasOcupadas = new javax.swing.JLabel();
        panCantProdutosActivos = new javax.swing.JPanel();
        lblProductosActivos = new javax.swing.JLabel();
        lblCantProductosActivos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panPrincipal.setMaximumSize(new java.awt.Dimension(1366, 768));
        panPrincipal.setMinimumSize(new java.awt.Dimension(1366, 768));
        panPrincipal.setPreferredSize(new java.awt.Dimension(1366, 768));
        panPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPrincipal1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        lblPrincipal1.setText("Bienvenido, Administrador");
        panPrincipal.add(lblPrincipal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        sep.setForeground(new java.awt.Color(18, 44, 79));
        panPrincipal.add(sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 1080, -1));

        panContenido.setBackground(new java.awt.Color(255, 255, 255));

        panVentasDiarias.setBackground(new java.awt.Color(221, 234, 246));
        panVentasDiarias.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));

        lblVentasDiarias.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblVentasDiarias.setForeground(new java.awt.Color(89, 83, 83));
        lblVentasDiarias.setText("Ventas del día");

        lblCantidadVentas.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblCantidadVentas.setText("jLabel1");

        javax.swing.GroupLayout panVentasDiariasLayout = new javax.swing.GroupLayout(panVentasDiarias);
        panVentasDiarias.setLayout(panVentasDiariasLayout);
        panVentasDiariasLayout.setHorizontalGroup(
            panVentasDiariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panVentasDiariasLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panVentasDiariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCantidadVentas)
                    .addComponent(lblVentasDiarias))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        panVentasDiariasLayout.setVerticalGroup(
            panVentasDiariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panVentasDiariasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCantidadVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVentasDiarias)
                .addGap(21, 21, 21))
        );

        panComandasDiarias.setBackground(new java.awt.Color(221, 234, 246));
        panComandasDiarias.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        panComandasDiarias.setMinimumSize(new java.awt.Dimension(100, 100));

        lblComandasDiarias.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblComandasDiarias.setForeground(new java.awt.Color(89, 83, 83));
        lblComandasDiarias.setText("Comandas hoy");

        lblNumComandas.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblNumComandas.setText("jLabel1");

        javax.swing.GroupLayout panComandasDiariasLayout = new javax.swing.GroupLayout(panComandasDiarias);
        panComandasDiarias.setLayout(panComandasDiariasLayout);
        panComandasDiariasLayout.setHorizontalGroup(
            panComandasDiariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panComandasDiariasLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panComandasDiariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumComandas)
                    .addComponent(lblComandasDiarias))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        panComandasDiariasLayout.setVerticalGroup(
            panComandasDiariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panComandasDiariasLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(lblNumComandas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblComandasDiarias)
                .addGap(21, 21, 21))
        );

        PanMesasDisponibles.setBackground(new java.awt.Color(221, 234, 246));
        PanMesasDisponibles.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        PanMesasDisponibles.setMinimumSize(new java.awt.Dimension(100, 100));

        lblMesasAbiertas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMesasAbiertas.setForeground(new java.awt.Color(89, 83, 83));
        lblMesasAbiertas.setText("Mesas Abiertas");

        lblNumMesasOcupadas.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblNumMesasOcupadas.setText("jLabel1");

        javax.swing.GroupLayout PanMesasDisponiblesLayout = new javax.swing.GroupLayout(PanMesasDisponibles);
        PanMesasDisponibles.setLayout(PanMesasDisponiblesLayout);
        PanMesasDisponiblesLayout.setHorizontalGroup(
            PanMesasDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanMesasDisponiblesLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(PanMesasDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumMesasOcupadas)
                    .addComponent(lblMesasAbiertas))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        PanMesasDisponiblesLayout.setVerticalGroup(
            PanMesasDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanMesasDisponiblesLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(lblNumMesasOcupadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMesasAbiertas)
                .addGap(21, 21, 21))
        );

        panCantProdutosActivos.setBackground(new java.awt.Color(221, 234, 246));
        panCantProdutosActivos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        panCantProdutosActivos.setMinimumSize(new java.awt.Dimension(100, 100));

        lblProductosActivos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProductosActivos.setForeground(new java.awt.Color(89, 83, 83));
        lblProductosActivos.setText("Productos activos");

        lblCantProductosActivos.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblCantProductosActivos.setText("jLabel1");

        javax.swing.GroupLayout panCantProdutosActivosLayout = new javax.swing.GroupLayout(panCantProdutosActivos);
        panCantProdutosActivos.setLayout(panCantProdutosActivosLayout);
        panCantProdutosActivosLayout.setHorizontalGroup(
            panCantProdutosActivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCantProdutosActivosLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panCantProdutosActivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCantProductosActivos)
                    .addComponent(lblProductosActivos))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        panCantProdutosActivosLayout.setVerticalGroup(
            panCantProdutosActivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCantProdutosActivosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCantProductosActivos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProductosActivos)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout panContenidoLayout = new javax.swing.GroupLayout(panContenido);
        panContenido.setLayout(panContenidoLayout);
        panContenidoLayout.setHorizontalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panContenidoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panComandasDiarias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanMesasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panVentasDiarias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panCantProdutosActivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        panContenidoLayout.setVerticalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panContenidoLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panVentasDiarias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panComandasDiarias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panCantProdutosActivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanMesasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        panPrincipal.add(panContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 177, 1150, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanMesasDisponibles;
    private javax.swing.JLabel lblCantProductosActivos;
    private javax.swing.JLabel lblCantidadVentas;
    private javax.swing.JLabel lblComandasDiarias;
    private javax.swing.JLabel lblMesasAbiertas;
    private javax.swing.JLabel lblNumComandas;
    private javax.swing.JLabel lblNumMesasOcupadas;
    private javax.swing.JLabel lblPrincipal1;
    private javax.swing.JLabel lblProductosActivos;
    private javax.swing.JLabel lblVentasDiarias;
    private javax.swing.JPanel panCantProdutosActivos;
    private javax.swing.JPanel panComandasDiarias;
    private javax.swing.JPanel panContenido;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JPanel panVentasDiarias;
    private javax.swing.JSeparator sep;
    // End of variables declaration//GEN-END:variables
    private org.itson.restaurante.utilerias.PanelHeader panelHeader;
    private org.itson.restaurante.utilerias.PanelMenu panelMenu;
    private org.itson.restaurante.utilerias.PanelNavegacionPantallasPrincipales panelNavegacion;
}
