
package org.itson.restaurante.presentacion;

import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.itson.restaurante.controladores.ControladorComandas;
import org.itson.restaurante.dtos.ComandaDTO;
import org.itson.restaurante.dtos.ProductoComandaDTO;
import org.itson.restaurante.utilerias.PanelHeader;
import org.itson.restaurante.utilerias.PanelNavegacionPantallasPrincipales;
import org.itson.restaurante.utilerias.utilerias;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author oliro
 */
public class PantallaDetallesComanda extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaDetallesComanda.class.getName());

    private PanelHeader panelHeader;
    private PanelNavegacionPantallasPrincipales panelNavegacion;
    
    private ControladorComandas control;
    private String folio;
    
    /**
     * Creates new form PantallaDetallesComanda
     */
    public PantallaDetallesComanda(ControladorComandas control, String folio) {
        initComponents();
        this.control = control;
        this.folio = folio;
        
        panelHeader = new PanelHeader();
        panelNavegacion = new PanelNavegacionPantallasPrincipales();
        
        panelPrincipal.add(panelHeader, new AbsoluteConstraints(0, 0, 1366, 130));
        panelPrincipal.add(panelNavegacion, new AbsoluteConstraints(0, 130, 1366, 45));
        
        utilerias.estilizarTabla(tblProductosComanda);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelContenido = new javax.swing.JPanel();
        lblPrincipal = new javax.swing.JLabel();
        sep = new javax.swing.JSeparator();
        btnVolver = new javax.swing.JButton();
        btnMarcarEntrega = new javax.swing.JButton();
        lblFolio = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblMesa = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductosComanda = new javax.swing.JTable();
        lblEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setPreferredSize(new java.awt.Dimension(1364, 770));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelContenido.setBackground(new java.awt.Color(255, 255, 255));
        panelContenido.setPreferredSize(new java.awt.Dimension(1365, 590));

        lblPrincipal.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        lblPrincipal.setText("Detalle comanda");

        sep.setForeground(new java.awt.Color(18, 44, 79));

        btnVolver.setBackground(new java.awt.Color(18, 44, 79));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setToolTipText("");
        btnVolver.setPreferredSize(new java.awt.Dimension(200, 32));
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        btnMarcarEntrega.setBackground(new java.awt.Color(18, 44, 79));
        btnMarcarEntrega.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMarcarEntrega.setForeground(new java.awt.Color(255, 255, 255));
        btnMarcarEntrega.setText("Marcar entrega");
        btnMarcarEntrega.addActionListener(this::btnMarcarEntregaActionPerformed);

        lblFolio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFolio.setText("Folio:");

        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFecha.setText("Fecha:");

        lblCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCliente.setText("Cliente:");

        lblMesa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMesa.setText("Mesa:");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotal.setText("Total:");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 400));

        tblProductosComanda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Comentario", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductosComanda.setPreferredSize(new java.awt.Dimension(800, 400));
        jScrollPane1.setViewportView(tblProductosComanda);

        lblEstado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEstado.setText("Estado:");

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrincipal)
                    .addComponent(sep, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelContenidoLayout.createSequentialGroup()
                        .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFolio)
                            .addComponent(lblCliente)
                            .addComponent(lblFecha))
                        .addGap(322, 322, 322)
                        .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMesa)
                            .addComponent(lblTotal)
                            .addComponent(lblEstado))))
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelContenidoLayout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMarcarEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(280, 280, 280))
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblPrincipal)
                .addGap(2, 2, 2)
                .addComponent(sep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFolio)
                    .addComponent(lblMesa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(lblEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(lblTotal))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMarcarEntrega)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1360, 595));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMarcarEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarEntregaActionPerformed
        control.marcarEntregaComanda(this, folio);
    }//GEN-LAST:event_btnMarcarEntregaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        control.mostarPantallaComandas(this);
    }//GEN-LAST:event_btnVolverActionPerformed

    public void llenarTabla(List<ProductoComandaDTO> lista) {
        
        DefaultTableModel modelo = (DefaultTableModel) tblProductosComanda.getModel();
        modelo.setRowCount(0); // Limpiamos la tabla
        
        if (lista == null || lista.isEmpty()) {
            return;
        }
        
        Double subtotal = 0d;
        for (ProductoComandaDTO producto : lista) {
            subtotal += producto.getSubtotal();
            Object[] fila = {
                producto.getNombreProducto(),
                producto.getCantidad(),
                producto.getDetalles(),
                producto.getSubtotal(),
            };
            modelo.addRow(fila);;
        }
        lblTotal.setText("$" + subtotal);
        
    }
    
    public void llenarCampos(ComandaDTO comanda) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        lblFolio.setText(lblFolio.getText() + " " + comanda.getFolio());
        lblFecha.setText(lblFecha.getText() + " " + comanda.getFechaHora().format(formatter));
        lblCliente.setText(lblCliente.getText() + " " +comanda.getNombreCompleto());
        lblMesa.setText(lblMesa.getText() + " " + String.valueOf(comanda.getNoMesa()));
        lblEstado.setText(lblEstado.getText() + " " + comanda.getEstado().toString());
    }
    
    public void mostarMensaje(String msj, boolean esError) {
        int tipo = esError ? JOptionPane.ERROR_MESSAGE : JOptionPane.INFORMATION_MESSAGE;
        JOptionPane.showMessageDialog(this, msj, "Sistema", tipo);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMarcarEntrega;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFolio;
    private javax.swing.JLabel lblMesa;
    private javax.swing.JLabel lblPrincipal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JSeparator sep;
    private javax.swing.JTable tblProductosComanda;
    // End of variables declaration//GEN-END:variables
}
