/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.itson.restaurante.presentacion;

import org.itson.restaurante.dtos.ClienteFrecuenteDTO;
import org.itson.restaurante.utilerias.utilerias;
import org.itson.restaurante.negocio.ClienteFrecuenteBO;
import org.itson.restaurante.negocio.IClienteFrecuenteBO;
import org.itson.restaurante.negocio.NegocioException;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import org.itson.restaurante.dtos.IngredienteDTO;
import org.itson.restaurante.negocio.IIngredientesBO;
import org.itson.restaurante.negocio.IngredientesBO;
import org.itson.restaurante.utilerias.PanelHeader;
import org.itson.restaurante.utilerias.PanelNavegacionPantallasPrincipales;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author joset
 */
public class PantallaBusquedaIngrediente extends javax.swing.JDialog {

    /**
     * Creates new form PantallaBusquedaClienteD
     */
    private IngredienteDTO ingredienteSeleccionado = null;
    private List<IngredienteDTO> listaIngredientes = new ArrayList<>();

    private final IIngredientesBO ingredienteBO = new IngredientesBO();

    private boolean alertaSinResultados = false;

    public PantallaBusquedaIngrediente(java.awt.Frame parent, boolean modal) {

        super(parent, modal);

        initComponents();
        panelHeader = new PanelHeader();
        panelNavegacion = new PanelNavegacionPantallasPrincipales();

        panPrincipal.add(panelHeader, new AbsoluteConstraints(0, 0, 1366, 130));
        panPrincipal.add(panelNavegacion, new AbsoluteConstraints(0, 130, 1366, 45));

        panelNavegacion.setPantallasNavegacion("Ingrediente", "Busqueda Ingrediente");

        utilerias.estilizarBotonSinFondo(btnCancelar);

        this.setLocationRelativeTo(null);

        inicializarTabla();

        this.txtBusqueda.setText("Buscar por nombre o unidad...");

        this.txtBusqueda.setForeground(Color.GRAY);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        lblPantalla = new javax.swing.JLabel();
        sep = new javax.swing.JSeparator();
        btnCancelar = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIngredientes = new javax.swing.JTable();
        btnSeleccionarCliente = new javax.swing.JButton();
        panContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busqueda Cliente");
        setResizable(false);

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panPrincipal.setMaximumSize(new java.awt.Dimension(1366, 768));
        panPrincipal.setPreferredSize(new java.awt.Dimension(1366, 768));
        panPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPantalla.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        lblPantalla.setText("Busqueda Ingrediente");
        panPrincipal.add(lblPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        sep.setForeground(new java.awt.Color(18, 44, 79));
        panPrincipal.add(sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 243, 1060, 10));

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(18, 44, 79));
        btnCancelar.setText("Cancelar ");
        btnCancelar.setOpaque(true);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panPrincipal.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 700, 190, -1));

        txtBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtBusqueda.setToolTipText("");
        txtBusqueda.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtBusqueda.setMinimumSize(new java.awt.Dimension(3, 32));
        txtBusqueda.setName(""); // NOI18N
        txtBusqueda.setPreferredSize(new java.awt.Dimension(3, 32));
        txtBusqueda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBusquedaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBusquedaFocusLost(evt);
            }
        });
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyPressed(evt);
            }
        });
        panPrincipal.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 262, 1060, -1));

        tblIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblIngredientes.setFillsViewportHeight(true);
        tblIngredientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblIngredientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblIngredientes);

        panPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 1060, 350));

        btnSeleccionarCliente.setBackground(new java.awt.Color(18, 44, 79));
        btnSeleccionarCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSeleccionarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarCliente.setText("Seleccionar");
        btnSeleccionarCliente.setToolTipText("");
        btnSeleccionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarClienteActionPerformed(evt);
            }
        });
        panPrincipal.add(btnSeleccionarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 700, 190, -1));

        panContenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panContenidoLayout = new javax.swing.GroupLayout(panContenido);
        panContenido.setLayout(panContenidoLayout);
        panContenidoLayout.setHorizontalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        panContenidoLayout.setVerticalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        panPrincipal.add(panContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 177, 1370, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        ingredienteSeleccionado = null;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtBusquedaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBusquedaFocusGained
        if (this.txtBusqueda.getText().equals("Buscar por nombre o unidad...")) {

            this.txtBusqueda.setText(" ");

            this.txtBusqueda.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtBusquedaFocusGained

    private void txtBusquedaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBusquedaFocusLost
        if (this.txtBusqueda.getText().isEmpty()) {

            this.txtBusqueda.setText("Buscar por nombre o unidad...");

            this.txtBusqueda.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtBusquedaFocusLost

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed

    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void tblIngredientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblIngredientesMouseClicked
        if (evt.getClickCount() == 2) {

            seleccionarIngredienteTabla();

        }
    }//GEN-LAST:event_tblIngredientesMouseClicked

    private void btnSeleccionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarClienteActionPerformed
        if (tblIngredientes.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this,
                    "Selecciona un ingrediente primero",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        seleccionarIngredienteTabla();
        this.dispose();
    }//GEN-LAST:event_btnSeleccionarClienteActionPerformed

    private void txtBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyPressed
        String textoBusqueda = this.txtBusqueda.getText().trim();
        try {
            listaIngredientes = ingredienteBO.consultarIngredientesFiltro(textoBusqueda);

            if (listaIngredientes.isEmpty()) {
                if (!alertaSinResultados && evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    JOptionPane.showMessageDialog(this,
                            "No se encontró ningún ingrediente",
                            "Sin resultados",
                            JOptionPane.INFORMATION_MESSAGE);
                    alertaSinResultados = true;
                }
                return;
            }
            alertaSinResultados= false;
            cargarIngredientes(listaIngredientes);
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(), 
                    "Aviso", 
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtBusquedaKeyPressed

    private void inicializarTabla() {

        String[] columnas = {"Id", "Nombre", "Unidad", "Stock", "Imagen"};//Columnas

        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {       // que no se pueda editar las celdas
                return false;
            }

        };

        tblIngredientes.setModel(modelo);

        tblIngredientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        tblIngredientes.setRowSelectionAllowed(true);

        utilerias.estilizarTabla(tblIngredientes);

        try {
            List<IngredienteDTO> ingrediente = ingredienteBO.consultarIngredientes();
            cargarIngredientes(ingrediente);
        } catch (NegocioException ex) {
             JOptionPane.showMessageDialog(this,
                    ex.getMessage(), 
                    "Aviso", 
                    JOptionPane.WARNING_MESSAGE);
        }
    }

    private void cargarIngredientes(List<IngredienteDTO> ingredientes) {

        DefaultTableModel modelo = (DefaultTableModel) this.tblIngredientes.getModel();

        modelo.setRowCount(0);

        for (IngredienteDTO i : ingredientes) {

            modelo.addRow(new Object[]{
                i.getId(),
                i.getNombre() ,
                i.getUnidadMedida(),
                i.getStock(),
                i.getImagen(),
            });
        }

        this.listaIngredientes = ingredientes;
    }

    private void seleccionarIngredienteTabla() {

        int fila = this.tblIngredientes.getSelectedRow();

        if (fila >= 0) {

            this.ingredienteSeleccionado = this.listaIngredientes.get(fila);

        }
    }

    public IngredienteDTO getIngredienteSeleccionado() {
        return this.ingredienteSeleccionado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSeleccionarCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPantalla;
    private javax.swing.JPanel panContenido;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JSeparator sep;
    private javax.swing.JTable tblIngredientes;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
    private org.itson.restaurante.utilerias.PanelHeader panelHeader;
    private org.itson.restaurante.utilerias.PanelNavegacionPantallasPrincipales panelNavegacion;
}
