
package org.itson.restaurante.presentacion;

import java.awt.Color;
import org.itson.restaurante.utilerias.PanelHeader;
import org.itson.restaurante.utilerias.PanelMenu;
import org.itson.restaurante.utilerias.PanelNavegacionPantallasPrincipales;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author oliro
 */
public class PantallaComandas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaComandas.class.getName());

    private PanelHeader panelHeader;
    private PanelMenu panelMenu;
    private PanelNavegacionPantallasPrincipales panelNavegacion;
    
    String placeholder = "Buscar por nombre, numero telefonico o correo..";
    
    /**
     * Creates new form PantallaComanda
     */
    public PantallaComandas() {
        initComponents();
        LlenarTabla();
        
        panelHeader = new PanelHeader();
        panelMenu = new PanelMenu();
        panelNavegacion = new PanelNavegacionPantallasPrincipales();
        
        panelPrincipal.add(panelHeader, new AbsoluteConstraints(0, 0, 1366, 130));
        panelPrincipal.add(panelMenu, new AbsoluteConstraints(0, 130, 215, 640));
        panelPrincipal.add(panelNavegacion, new AbsoluteConstraints(215, 130, 1151, 45));
        
        panelNavegacion.setPantallasNavegacion("Comandas", "Lista");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelContenido = new javax.swing.JPanel();
        lblPrincipal1 = new javax.swing.JLabel();
        sep = new javax.swing.JSeparator();
        btnDetalles = new javax.swing.JButton();
        btnNuevaComanda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblComandas = new javax.swing.JTable();
        txtFiltro = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Comandas");

        panelPrincipal.setPreferredSize(new java.awt.Dimension(1364, 770));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelContenido.setBackground(new java.awt.Color(255, 255, 255));
        panelContenido.setPreferredSize(new java.awt.Dimension(1150, 590));

        lblPrincipal1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        lblPrincipal1.setText("Comandas");

        sep.setForeground(new java.awt.Color(18, 44, 79));

        btnDetalles.setBackground(new java.awt.Color(18, 44, 79));
        btnDetalles.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDetalles.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalles.setText("Detalles");
        btnDetalles.setToolTipText("");
        btnDetalles.addActionListener(this::btnDetallesActionPerformed);

        btnNuevaComanda.setBackground(new java.awt.Color(18, 44, 79));
        btnNuevaComanda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNuevaComanda.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaComanda.setText("Nueva comanda");
        btnNuevaComanda.addActionListener(this::btnNuevaComandaActionPerformed);

        tblComandas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Folio", "Fecha/Hora", "Mesa", "Cliente", "Total", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblComandas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblComandas);
        if (tblComandas.getColumnModel().getColumnCount() > 0) {
            tblComandas.getColumnModel().getColumn(0).setResizable(false);
            tblComandas.getColumnModel().getColumn(1).setResizable(false);
            tblComandas.getColumnModel().getColumn(2).setResizable(false);
            tblComandas.getColumnModel().getColumn(3).setResizable(false);
            tblComandas.getColumnModel().getColumn(4).setResizable(false);
            tblComandas.getColumnModel().getColumn(5).setResizable(false);
        }

        txtFiltro.setForeground(new java.awt.Color(128, 128, 128));
        txtFiltro.setText("Buscar por nombre, numero telefonico o correo..");
        txtFiltro.setPreferredSize(new java.awt.Dimension(920, 30));
        txtFiltro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFiltroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFiltroFocusLost(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(150, 30));

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelContenidoLayout.createSequentialGroup()
                        .addComponent(btnDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnNuevaComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPrincipal1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelContenidoLayout.createSequentialGroup()
                            .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1)))
                .addGap(25, 25, 25))
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblPrincipal1)
                .addGap(2, 2, 2)
                .addComponent(sep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDetalles)
                    .addComponent(btnNuevaComanda))
                .addGap(49, 49, 49))
        );

        panelPrincipal.add(panelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 175, 1150, 595));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesActionPerformed

    }//GEN-LAST:event_btnDetallesActionPerformed

    private void btnNuevaComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaComandaActionPerformed
        Controlador.getIntancia().abrirFormularioComanda(this);
    }//GEN-LAST:event_btnNuevaComandaActionPerformed

    private void txtFiltroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFiltroFocusGained
        if (txtFiltro.getText().equals(placeholder)) {
            txtFiltro.setText("");
            txtFiltro.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtFiltroFocusGained

    private void txtFiltroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFiltroFocusLost
        if (txtFiltro.getText().isBlank()) {
            txtFiltro.setText(placeholder);
            txtFiltro.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtFiltroFocusLost

    private void LlenarTabla() {
        
    }    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaComandas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalles;
    private javax.swing.JButton btnNuevaComanda;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPrincipal1;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JSeparator sep;
    private javax.swing.JTable tblComandas;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
