/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.restaurante.presentacion;

import java.io.File;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.itson.restaurante.negocio.NegocioException;
import org.itson.restaurante.negocio.ReporteBO;
import org.itson.restaurante.utilerias.PanelHeader;
import org.itson.restaurante.utilerias.PanelMenu;
import org.itson.restaurante.utilerias.PanelNavegacionPantallasPrincipales;
import org.itson.restaurante.utilerias.utilerias;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author joset
 */
public class PantallaReportesClientes extends javax.swing.JFrame {

    /**
     * Creates new form PantallaReportes
     */
    public PantallaReportesClientes() {
        initComponents();
        utilerias.estilizarBotonPrimario(btnGuardarPDF);
        setLocationRelativeTo(null);
        this.setResizable(false);
        
        utilerias.aplicarIcono(this);

        panelHeader = new PanelHeader();
        panelMenu = new PanelMenu();
        panelNavegacion = new PanelNavegacionPantallasPrincipales();

        panPrinciapl.add(panelHeader, new AbsoluteConstraints(0, 0, 1366, 130));
        panPrinciapl.add(panelMenu, new AbsoluteConstraints(0, 130, 215, 640));
        panPrinciapl.add(panelNavegacion, new AbsoluteConstraints(215, 130, 1151, 45));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrinciapl = new javax.swing.JPanel();
        btnGuardarPDF = new javax.swing.JButton();
        btnConsultarPDf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panPrinciapl.setBackground(new java.awt.Color(255, 255, 255));
        panPrinciapl.setMaximumSize(new java.awt.Dimension(1366, 768));
        panPrinciapl.setMinimumSize(new java.awt.Dimension(1366, 768));
        panPrinciapl.setPreferredSize(new java.awt.Dimension(1366, 768));

        btnGuardarPDF.setBackground(new java.awt.Color(18, 44, 79));
        btnGuardarPDF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGuardarPDF.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarPDF.setText("Guardar en PDF");
        btnGuardarPDF.setToolTipText("");
        btnGuardarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPDFActionPerformed(evt);
            }
        });

        btnConsultarPDf.setBackground(new java.awt.Color(18, 44, 79));
        btnConsultarPDf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnConsultarPDf.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarPDf.setText("Consultar Detalles");
        btnConsultarPDf.setToolTipText("");
        btnConsultarPDf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPDfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panPrinciaplLayout = new javax.swing.GroupLayout(panPrinciapl);
        panPrinciapl.setLayout(panPrinciaplLayout);
        panPrinciaplLayout.setHorizontalGroup(
            panPrinciaplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrinciaplLayout.createSequentialGroup()
                .addGap(437, 437, 437)
                .addComponent(btnConsultarPDf, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(689, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrinciaplLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(339, 339, 339))
        );
        panPrinciaplLayout.setVerticalGroup(
            panPrinciaplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrinciaplLayout.createSequentialGroup()
                .addContainerGap(392, Short.MAX_VALUE)
                .addComponent(btnConsultarPDf)
                .addGap(175, 175, 175)
                .addComponent(btnGuardarPDF)
                .addGap(137, 137, 137))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panPrinciapl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panPrinciapl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPDFActionPerformed
        try {
            LocalDate inicio = LocalDate.now();
            LocalDate fin = LocalDate.now();
            ReporteBO bo = new ReporteBO();
            JasperPrint jp = bo.generarReporteCliente(inicio, fin);

            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setSelectedFile(new File("ReporteClientes.pdf"));

            if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {

                String ruta = fileChooser.getSelectedFile().getAbsolutePath();

                if (!ruta.endsWith(".pdf")) {
                    ruta += ".pdf";
                }

                JasperExportManager.exportReportToPdfFile(jp, ruta);

                JOptionPane.showMessageDialog(this, "PDF generado correctamente.");
            }

        } catch (NegocioException | JRException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        } catch (Exception ex) {
            System.getLogger(PantallaReportesClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnGuardarPDFActionPerformed

    private void btnConsultarPDfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPDfActionPerformed
        try {
            LocalDate inicio = LocalDate.now();//cambiar por el campo de fecha real
            LocalDate fin = LocalDate.now();//cambiar por el campo de fecha real

            ReporteBO bo = new ReporteBO();
            JasperPrint jp = bo.generarReporteCliente(inicio, fin);
            if (jp != null) {
                JasperViewer.viewReport(jp, false);
            }

        } catch (NegocioException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        } catch (Exception ex) {
            if (ex.getMessage().contains("FileNotFoundException")) {
                JOptionPane.showMessageDialog(this,
                        "No se pudo crear el archivo. Verifica que:\n"
                        + "1. La carpeta de destino existe.\n"
                        + "2. No tienes el PDF abierto en otro programa.\n"
                        + "3. Tienes permisos para escribir en esa carpeta (OneDrive).",
                        "Error de Acceso", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error inesperado: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnConsultarPDfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaReportesClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaReportesClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaReportesClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaReportesClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaReportesClientes().setVisible(true);
            }

        });
    }
    
    private PanelHeader panelHeader;
    private PanelMenu panelMenu;
    private PanelNavegacionPantallasPrincipales panelNavegacion;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarPDf;
    private javax.swing.JButton btnGuardarPDF;
    private javax.swing.JPanel panPrinciapl;
    // End of variables declaration//GEN-END:variables
}
