/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.restaurante.presentacion;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import org.itson.restaurante.controladores.Controlador;
import org.itson.restaurante.controladores.ControladorProductos;
import org.itson.restaurante.dtos.EstadoProducto;
import org.itson.restaurante.dtos.IngredienteDTO;
import org.itson.restaurante.dtos.IngredienteRecetaDTO;
import org.itson.restaurante.dtos.NuevoProductoDTO;
import org.itson.restaurante.dtos.ProductoDTO;
import org.itson.restaurante.dtos.TipoProducto;
import org.itson.restaurante.negocio.NegocioException;
import org.itson.restaurante.utilerias.PanelHeader;
import org.itson.restaurante.utilerias.PanelMenu;
import org.itson.restaurante.utilerias.PanelNavegacionPantallasPrincipales;
import org.itson.restaurante.utilerias.utilerias;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author juanl
 */
public class PantallaFormularioProducto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaFormularioProducto.class.getName());

    private ControladorProductos controlador;
    private Controlador controladorBase;
    private ProductoDTO productoSeleccionado = null;
    private IngredienteRecetaDTO IngredienteSeleccionado = null;
    private IngredienteDTO ingredienteEncontrado = null;
    private List<IngredienteRecetaDTO> ListIngredientes = new ArrayList<>();
    private byte[] imagen;
    /**
     * Creates new form PantallaProductos
     */
    public PantallaFormularioProducto(ControladorProductos controlador, ProductoDTO producto,Controlador controladorBase,IngredienteDTO ingredienteEncontrado) {
        this.controlador = controlador;
        this.controladorBase = controladorBase;
        this.productoSeleccionado = producto;
        this.ingredienteEncontrado = ingredienteEncontrado;
        initComponents();
        this.setResizable(false);
        inicializarTabla();
        javax.swing.DefaultComboBoxModel modelo = new javax.swing.DefaultComboBoxModel();
        for (TipoProducto tipo : TipoProducto.values()) {
            modelo.addElement(tipo);
        }
        cmbTipo.setModel(modelo);
        if (this.productoSeleccionado != null) {
            Long id = this.productoSeleccionado.getId(); 
            this.cmbTipo.setSelectedItem(productoSeleccionado.getTipoProducto());
        } else {
            this.ListIngredientes = new ArrayList<>();
        }
        cargarDatosProducto();
        utilerias.aplicarIcono(this);
        
        
        
        
        panelHeader = new PanelHeader();
        panelMenu = new PanelMenu();
        panelNavegacion = new PanelNavegacionPantallasPrincipales();

        PanelPrincipal.add(panelHeader, new AbsoluteConstraints(0, 0, 1366, 130));
        PanelPrincipal.add(panelNavegacion, new AbsoluteConstraints(0, 130, 1366, 45));
        
        
        PanelPrincipal.add(panelContenido, new AbsoluteConstraints(230, 180, 1366, 590));
        panelNavegacion.setPantallasNavegacion("Busqueda de Producto", "Editar/Agregar ");
        
        utilerias.estilizarBotonSinFondo(btnCancelar);
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        panelContenido1 = new javax.swing.JPanel();
        lblTitulo2 = new javax.swing.JLabel();
        btnGuardarProducto = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnBuscarIngrediente = new javax.swing.JButton();
        sep = new javax.swing.JSeparator();
        txtDescripcion = new javax.swing.JTextField();
        sep1 = new javax.swing.JSeparator();
        lblTitulo1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        lblTipo = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        lblImagen = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        lblPrecio1 = new javax.swing.JLabel();
        txtImagen = new javax.swing.JTextField();
        btnBuscarImagen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIngredientes = new javax.swing.JTable();
        btnEliminarIngrediente = new javax.swing.JButton();
        panelContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrincipal.setMinimumSize(new java.awt.Dimension(1366, 768));
        PanelPrincipal.setPreferredSize(new java.awt.Dimension(1366, 768));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelContenido1.setBackground(new java.awt.Color(255, 255, 255));
        panelContenido1.setPreferredSize(new java.awt.Dimension(1366, 590));

        lblTitulo2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        lblTitulo2.setText("Ingredientes del producto");

        btnGuardarProducto.setBackground(new java.awt.Color(18, 44, 79));
        btnGuardarProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGuardarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarProducto.setText("Guardar");
        btnGuardarProducto.setToolTipText("");
        btnGuardarProducto.addActionListener(this::btnGuardarProductoActionPerformed);

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnBuscarIngrediente.setBackground(new java.awt.Color(18, 44, 79));
        btnBuscarIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscarIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarIngrediente.setToolTipText("");
        btnBuscarIngrediente.setLabel("Buscar Ingrediente");
        btnBuscarIngrediente.addActionListener(this::btnBuscarIngredienteActionPerformed);

        sep.setForeground(new java.awt.Color(18, 44, 79));

        txtDescripcion.addActionListener(this::txtDescripcionActionPerformed);

        sep1.setForeground(new java.awt.Color(18, 44, 79));

        lblTitulo1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        lblTitulo1.setText("Fomulario - Nuevo/Editar Producto");

        jLabel1.setText("Nombre");

        cmbTipo.addActionListener(this::cmbTipoActionPerformed);

        lblTipo.setText("Tipo");

        txtPrecio.addActionListener(this::txtPrecioActionPerformed);

        lblImagen.setText("Imagen");

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        lblDescripcion.setText("Descripcion");

        lblPrecio1.setText("Precio");

        txtImagen.addActionListener(this::txtImagenActionPerformed);

        btnBuscarImagen.setBackground(new java.awt.Color(18, 44, 79));
        btnBuscarImagen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscarImagen.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarImagen.setText("buscar");
        btnBuscarImagen.setToolTipText("");
        btnBuscarImagen.addActionListener(this::btnBuscarImagenActionPerformed);

        tblIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblIngredientes);

        btnEliminarIngrediente.setBackground(new java.awt.Color(18, 44, 79));
        btnEliminarIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEliminarIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarIngrediente.setText("Eliminar Ingrediente");
        btnEliminarIngrediente.setToolTipText("");
        btnEliminarIngrediente.addActionListener(this::btnEliminarIngredienteActionPerformed);

        javax.swing.GroupLayout panelContenido1Layout = new javax.swing.GroupLayout(panelContenido1);
        panelContenido1.setLayout(panelContenido1Layout);
        panelContenido1Layout.setHorizontalGroup(
            panelContenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenido1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelContenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sep1)
                    .addComponent(sep)
                    .addGroup(panelContenido1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelContenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelContenido1Layout.createSequentialGroup()
                                .addGroup(panelContenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelContenido1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(panelContenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDescripcion)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelContenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelContenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelContenido1Layout.createSequentialGroup()
                                        .addGap(147, 147, 147)
                                        .addGroup(panelContenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panelContenido1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panelContenido1Layout.createSequentialGroup()
                                                .addComponent(txtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnBuscarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(panelContenido1Layout.createSequentialGroup()
                                        .addGap(158, 158, 158)
                                        .addComponent(lblPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(61, 61, 61))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenido1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnEliminarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnGuardarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenido1Layout.createSequentialGroup()
                        .addComponent(lblTitulo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelContenido1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 71, Short.MAX_VALUE)))
                .addGap(51, 51, 51))
            .addGroup(panelContenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContenido1Layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(lblTitulo1)
                    .addContainerGap(742, Short.MAX_VALUE)))
        );
        panelContenido1Layout.setVerticalGroup(
            panelContenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenido1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(sep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTipo)
                    .addComponent(lblPrecio1))
                .addGap(7, 7, 7)
                .addGroup(panelContenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(cmbTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(panelContenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(lblImagen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarImagen, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtImagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtDescripcion))
                .addGap(14, 14, 14)
                .addComponent(sep1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo2)
                    .addComponent(btnBuscarIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelContenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContenido1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(panelContenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(btnGuardarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 57, 57))
                    .addGroup(panelContenido1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(panelContenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContenido1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lblTitulo1)
                    .addContainerGap(526, Short.MAX_VALUE)))
        );

        PanelPrincipal.add(panelContenido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        panelContenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProductoActionPerformed
            TipoProducto tipoSeleccionado = (TipoProducto) cmbTipo.getSelectedItem();
            String nombreNuevo = txtNombre.getText();
            String descripcionNueva = txtDescripcion.getText();
            Double precioNuevo = 0.0; 
            String textoPrecio = txtPrecio.getText();

            if (!textoPrecio.isEmpty()) {
                precioNuevo = Double.parseDouble(textoPrecio); 
            }
            try{
            if(productoSeleccionado != null){

                Long idOriginal = productoSeleccionado.getId();
                EstadoProducto estadoOriginal = productoSeleccionado.getEstado(); 
                ProductoDTO productoActualizado = new ProductoDTO(
                    idOriginal,
                    nombreNuevo,
                    precioNuevo,
                    tipoSeleccionado, 
                    estadoOriginal,
                    descripcionNueva,
                    this.imagen,      
                    this.ListIngredientes 
                );
                controlador.ActualizarProducto(productoActualizado);
                productoSeleccionado.setReceta(ListIngredientes);

                JOptionPane.showMessageDialog(this, "Producto actualizado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
            this.productoSeleccionado = productoActualizado;
            }else{
                NuevoProductoDTO productoNuevo = new NuevoProductoDTO(
                nombreNuevo,
                precioNuevo,
                tipoSeleccionado, 
                descripcionNueva,
                this.imagen,      
                this.ListIngredientes
            );

               controlador.registrar(productoNuevo); 
            
            JOptionPane.showMessageDialog(this, "Producto registrado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }
            

        
        } catch (NegocioException ex) {
            System.getLogger(PantallaFormularioProducto.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnGuardarProductoActionPerformed

    private void btnBuscarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIngredienteActionPerformed
        IngredienteDTO ingredienteElegido =
            controladorBase.abrirBusquedaIngredientesProductos(this);

        if (ingredienteElegido == null) {
            return; 
        }

        try {
            agregarIngredienteAlProducto(ingredienteElegido);
        } catch (NegocioException ex) {
            System.getLogger(PantallaFormularioProducto.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        
        
    }//GEN-LAST:event_btnBuscarIngredienteActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        controlador.mostarPantallaProductos(this);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed

    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void txtImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImagenActionPerformed

    private void btnBuscarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarImagenActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
                "Imágenes", "jpg", "jpeg", "png", "gif"
        ));

        int resultado = fileChooser.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            this.txtImagen.setText(archivo.getAbsolutePath());

            try {
                imagen = java.nio.file.Files.readAllBytes(archivo.toPath());
                ImageIcon icono = new ImageIcon(imagen);
                Image escalada = icono.getImage().getScaledInstance(306, 221, Image.SCALE_SMOOTH);
                this.lblImagen.setIcon(new ImageIcon(escalada));
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error al cargar la imagen");
            }
        }
    }//GEN-LAST:event_btnBuscarImagenActionPerformed

    private void btnEliminarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarIngredienteActionPerformed
        int fila = this.tblIngredientes.getSelectedRow();

        if (fila < 0) {
            JOptionPane.showMessageDialog(this,
                    "Selecciona un ingrediente primero",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int filaModelo = tblIngredientes.convertRowIndexToModel(fila);
        this.productoSeleccionado.getReceta().remove(filaModelo);
        this.ListIngredientes.remove(filaModelo);

        try {
            cargarIngredientes(this.ListIngredientes);
        } catch (NegocioException ex) {
            System.getLogger(PantallaFormularioProducto.class.getName())
                    .log(System.Logger.Level.ERROR, (String) null, ex);
     }
 
    }//GEN-LAST:event_btnEliminarIngredienteActionPerformed

    public void inicializarTabla(){
    
        String[] columnas = {"Nombre","Unidad","Cantidad"};
        
        DefaultTableModel modelo = new DefaultTableModel(columnas,0){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
            @Override
            public Class<?> getColumnClass(int columnIndex) { 
                return switch (columnIndex) {
                    case 0 -> String.class;    
                    case 1 -> String.class;    
                    case 2 -> Float.class;   
                    default -> Object.class;
                };
            }
        };
        tblIngredientes.setModel(modelo);
        utilerias.estilizarTablaProductos(tblIngredientes);
        if (this.productoSeleccionado != null) {
        try{
            List<IngredienteRecetaDTO> listaIngredientes = controlador.consultarProductoID(productoSeleccionado.getId()).getReceta();
            cargarIngredientes(listaIngredientes);
        }catch(NegocioException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
        }
       }
    }
    
    private void seleccionarIngredienteTabla(){
        int fila = this.tblIngredientes.getSelectedRow();
        if(fila >= 0){
            this.IngredienteSeleccionado = this.ListIngredientes.get(fila);
        }
    }

        private void cargarIngredientes(List<IngredienteRecetaDTO> ingredientes) throws NegocioException {
        DefaultTableModel modelo = (DefaultTableModel) this.tblIngredientes.getModel();

        modelo.setRowCount(0);

        
        for (IngredienteRecetaDTO i : ingredientes) {
        String unidad = "Desconocida"; 

        try {
            if (controlador != null) {
                IngredienteDTO ing = controlador.ConsultarIngrediente(i.getIdIngrediente());

                if (ing != null && ing.getUnidadMedida() != null) {
                    unidad = ing.getUnidadMedida().toString();
                }
            } else {
                System.err.println("¡Ojo! El controlador está null en este punto.");
            }
        } catch (Exception ex) {
            System.err.println("Error al buscar unidad de medida: " + ex.getMessage());
        }

        modelo.addRow(new Object[]{
            i.getNombre(),
            unidad,
            i.getCantidad()
        });
        }
        this.ListIngredientes = ingredientes;
     }
        

        public IngredienteRecetaDTO getIngredienteSeleccionado() {
            return IngredienteSeleccionado;
        }
    
    
    private void cargarDatosProducto(){
        if (this.productoSeleccionado != null) {
            this.txtNombre.setText(productoSeleccionado.getNombre());
            this.txtDescripcion.setText(productoSeleccionado.getDescripcion());
            this.txtPrecio.setText(productoSeleccionado.getPrecio().toString());



             if (productoSeleccionado.getImagen() != null) {
                ImageIcon icono = new ImageIcon(productoSeleccionado.getImagen());
                Image escalada = icono.getImage().getScaledInstance(306, 221, Image.SCALE_SMOOTH);
                this.lblImagen.setIcon(new ImageIcon(escalada));
            }
        }
    }
    
    
    private ImageIcon convertirImagen(byte[] imagenBytes) {
        ImageIcon icono;
        if (imagenBytes == null) {
            icono = new ImageIcon("src/main/java/org/itson/restaurante/recursos/placeHolderProductoSinSubir.png");
        } else {
            icono = new ImageIcon(imagenBytes);
        }
        Image imgEscalada = icono.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        return new ImageIcon(imgEscalada);
    }
    
    private void agregarIngredienteAlProducto(IngredienteDTO ingrediente) throws NegocioException {

        IngredienteRecetaDTO nuevo = new IngredienteRecetaDTO(
                ingrediente.getId(),
                ingrediente.getNombre(),
                1.0   
        );

        ListIngredientes.add(nuevo);
        cargarIngredientes(ListIngredientes);

        try {
            cargarIngredientes(ListIngredientes);
        } catch (NegocioException ex) {
            ex.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    private PanelHeader panelHeader;
    private PanelMenu panelMenu;
    private PanelNavegacionPantallasPrincipales panelNavegacion;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton btnBuscarImagen;
    private javax.swing.JButton btnBuscarIngrediente;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminarIngrediente;
    private javax.swing.JButton btnGuardarProducto;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblPrecio1;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelContenido1;
    private javax.swing.JSeparator sep;
    private javax.swing.JSeparator sep1;
    private javax.swing.JTable tblIngredientes;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtImagen;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
