
package org.itson.restaurante.presentacion;

import org.itson.restaurante.dtos.ClienteFrecuenteDTO;
import org.itson.restaurante.utilerias.utilerias;
import org.itson.restaurante.negocio.NegocioException;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import org.itson.restaurante.controladores.ControladorClientes;
import org.itson.restaurante.utilerias.PanelHeader;
import org.itson.restaurante.utilerias.PanelNavegacionPantallasPrincipales;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author joset
 */
public class PantallaBusquedaClienteD extends javax.swing.JDialog {

    /**
     * Creates new form PantallaBusquedaClienteD
     */
    private ClienteFrecuenteDTO clienteSeleccionado = null;
    private List<ClienteFrecuenteDTO> listaClientes = new ArrayList<>();
    private boolean alertaSinResultados = false;

    ControladorClientes control;
    
    public PantallaBusquedaClienteD(java.awt.Frame parent, boolean modal, ControladorClientes control) {
        super(parent, modal);
        
        initComponents();
        this.control = control;
        panelHeader = new PanelHeader();
        panelNavegacion = new PanelNavegacionPantallasPrincipales();

        panPrincipal.add(panelHeader, new AbsoluteConstraints(0, 0, 1366, 130));
        panPrincipal.add(panelNavegacion, new AbsoluteConstraints(0, 130, 1366, 45));

        panelNavegacion.setPantallasNavegacion("Clientes Frecuentes", "Busqueda Cliente");

        utilerias.estilizarBotonSinFondo(btnCancelar);

        this.setLocationRelativeTo(null);

        inicializarTabla();

        this.txtBusqueda.setText("Buscar por nombre, numero telefonico o correo..");

        this.txtBusqueda.setForeground(Color.GRAY);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        lblPantalla = new javax.swing.JLabel();
        sep = new javax.swing.JSeparator();
        btnCancelar = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnSeleccionarCliente = new javax.swing.JButton();
        panContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busqueda Cliente");
        setResizable(false);

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panPrincipal.setMaximumSize(new java.awt.Dimension(1366, 768));
        panPrincipal.setPreferredSize(new java.awt.Dimension(1366, 768));
        panPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPantalla.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        lblPantalla.setText("Busqueda Cliente");
        panPrincipal.add(lblPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        sep.setForeground(new java.awt.Color(18, 44, 79));
        panPrincipal.add(sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 243, 1060, 10));

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(18, 44, 79));
        btnCancelar.setText("Cancelar ");
        btnCancelar.setOpaque(true);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panPrincipal.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 700, 190, -1));

        txtBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtBusqueda.setToolTipText("");
        txtBusqueda.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtBusqueda.setMinimumSize(new java.awt.Dimension(3, 32));
        txtBusqueda.setName(""); // NOI18N
        txtBusqueda.setPreferredSize(new java.awt.Dimension(3, 32));
        txtBusqueda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBusquedaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBusquedaFocusLost(evt);
            }
        });
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyPressed(evt);
            }
        });
        panPrincipal.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 262, 1060, -1));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblClientes.setFillsViewportHeight(true);
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        panPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 1060, 350));

        btnSeleccionarCliente.setBackground(new java.awt.Color(18, 44, 79));
        btnSeleccionarCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSeleccionarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarCliente.setText("Seleccionar");
        btnSeleccionarCliente.setToolTipText("");
        btnSeleccionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarClienteActionPerformed(evt);
            }
        });
        panPrincipal.add(btnSeleccionarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 700, 190, -1));

        panContenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panContenidoLayout = new javax.swing.GroupLayout(panContenido);
        panContenido.setLayout(panContenidoLayout);
        panContenidoLayout.setHorizontalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        panContenidoLayout.setVerticalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        panPrincipal.add(panContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 177, 1370, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        clienteSeleccionado = null;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtBusquedaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBusquedaFocusGained
        if (this.txtBusqueda.getText().equals("Buscar por nombre, numero telefonico o correo..")) {

            this.txtBusqueda.setText(" ");

            this.txtBusqueda.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtBusquedaFocusGained

    private void txtBusquedaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBusquedaFocusLost
        if (this.txtBusqueda.getText().isEmpty()) {

            this.txtBusqueda.setText("Buscar por nombre, numero telefonico o correo..");

            this.txtBusqueda.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtBusquedaFocusLost

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed

    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        if (evt.getClickCount() == 2) {

            seleccionarClienteTabla();
            this.dispose();
        }
    }//GEN-LAST:event_tblClientesMouseClicked

    private void btnSeleccionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarClienteActionPerformed
        if (tblClientes.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this,
                    "Selecciona un cliente primero",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        seleccionarClienteTabla();
        this.dispose();
    }//GEN-LAST:event_btnSeleccionarClienteActionPerformed

/**
 * Realiza la búsqueda de clientes conforme el usuario escribe en el campo
 * de búsqueda y actualiza la tabla con los resultados encontrados.
 * 
 * @param evt Evento de tecla presionada
 */
    private void txtBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyPressed
        String textoBusqueda = this.txtBusqueda.getText().trim();
        try {
            listaClientes = control.consultarClientesFiltro(textoBusqueda);

            if (listaClientes.isEmpty()) {
                if (!alertaSinResultados && evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    JOptionPane.showMessageDialog(this,
                            "No se encontró ningún cliente",
                            "Sin resultados",
                            JOptionPane.INFORMATION_MESSAGE);
                    alertaSinResultados = true;
                }
                return;
            }
            alertaSinResultados= false;
            cargarClientes(listaClientes);
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtBusquedaKeyPressed

    private void inicializarTabla() {

        String[] columnas = {"Id", "Nombre", "Teléfono", "Correo", "Visitas", "Total gastado", "Puntos", "Últ. comanda"};//Columnas

        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {       // esto es lo que hace no se pueda editar las celdas
                return false;
            }

        };

        tblClientes.setModel(modelo);

        tblClientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        tblClientes.setRowSelectionAllowed(true);

        utilerias.estilizarTabla(tblClientes);

        try {
            listaClientes  = control.consultarClientes();
            cargarClientes(listaClientes);
        } catch (NegocioException ex) {
             JOptionPane.showMessageDialog(this, ex.getMessage(),"Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void cargarClientes(List<ClienteFrecuenteDTO> clientes) {

        DefaultTableModel modelo = (DefaultTableModel) this.tblClientes.getModel();

        modelo.setRowCount(0);

        for (ClienteFrecuenteDTO c : clientes) {

            modelo.addRow(new Object[]{
                c.getId(),
                c.getNombre() + " " + c.getApellidoPaterno() + " " + c.getApellidoMaterno(),
                c.getTelefono(),
                c.getCorreo(),
                c.getNumeroVisitas(),
                "$" + String.format("%.2f", c.getTotalGastado()),
                c.getPuntosAcumulados() + " pts",
                c.getFechaUltimaComanda()

            });
        }

        this.listaClientes = clientes;
    }

    private void seleccionarClienteTabla() {

        int fila = this.tblClientes.getSelectedRow();

        if (fila >= 0) {

            this.clienteSeleccionado = this.listaClientes.get(fila);

        }
    }

    public ClienteFrecuenteDTO getClienteSeleccionado() {
        return this.clienteSeleccionado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSeleccionarCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPantalla;
    private javax.swing.JPanel panContenido;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JSeparator sep;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
    private org.itson.restaurante.utilerias.PanelHeader panelHeader;
    private org.itson.restaurante.utilerias.PanelNavegacionPantallasPrincipales panelNavegacion;
}
