/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.restaurante.presentacion;

import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import org.itson.restaurante.controladores.Controlador;
import org.itson.restaurante.controladores.ControladorProductos;
import org.itson.restaurante.dtos.ProductoDTO;
import org.itson.restaurante.dtos.TipoProducto;
import org.itson.restaurante.negocio.NegocioException;
import org.itson.restaurante.utilerias.PanelHeader;
import org.itson.restaurante.utilerias.PanelMenu;
import org.itson.restaurante.utilerias.PanelNavegacionPantallasPrincipales;
import org.itson.restaurante.utilerias.utilerias;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author juanl
 */
public class PantallaBusquedaProductos extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaBusquedaProductos.class.getName());

    private ControladorProductos controlador;
    private ProductoDTO productoSeleccionado = null;
    private List<ProductoDTO> Listproductos = new ArrayList<>();
    /**
     * Creates new form PantallaProductos
     */
    public PantallaBusquedaProductos(java.awt.Frame parent, boolean modal, ControladorProductos controlador) {
        this.controlador = controlador;
        initComponents();
        inicializarTabla();
        
        this.txtNombre.setText("Buscar por nombre");
        
        panelHeader = new PanelHeader();
        panelMenu = new PanelMenu();
        panelNavegacion = new PanelNavegacionPantallasPrincipales();

        PanelPrincipal.add(panelHeader, new AbsoluteConstraints(0, 0, 1366, 130));
        PanelPrincipal.add(panelNavegacion, new AbsoluteConstraints(0, 130, 1366, 45));
        
        
        PanelPrincipal.add(panelContenido, new AbsoluteConstraints(230, 180, 1366, 590));
        panelNavegacion.setPantallasNavegacion("Menu Productos", "Busqueda de Producto ");
        
        utilerias.estilizarBotonSinFondo(btnCancelar);
        
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtNombre.getText().equals("Buscar por nombre")) {
                    txtNombre.setText("");
                    txtNombre.setForeground(new java.awt.Color(0, 0, 0)); 
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtNombre.getText().isEmpty()) {
                    txtNombre.setForeground(new java.awt.Color(153, 153, 153));
                    txtNombre.setText("Buscar por nombre");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        panelContenido1 = new javax.swing.JPanel();
        lblITitulo1 = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        sep = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        txtNombre = new javax.swing.JTextField();
        cmbCategorias = new javax.swing.JComboBox<>();
        panelContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrincipal.setMinimumSize(new java.awt.Dimension(1366, 768));
        PanelPrincipal.setPreferredSize(new java.awt.Dimension(1366, 768));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelContenido1.setBackground(new java.awt.Color(255, 255, 255));
        panelContenido1.setPreferredSize(new java.awt.Dimension(1366, 590));

        lblITitulo1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        lblITitulo1.setText("Busqueda Producto");

        btnSeleccionar.setBackground(new java.awt.Color(18, 44, 79));
        btnSeleccionar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.setToolTipText("");
        btnSeleccionar.addActionListener(this::btnSeleccionarActionPerformed);

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnBuscar.setBackground(new java.awt.Color(18, 44, 79));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        sep.setForeground(new java.awt.Color(18, 44, 79));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        cmbCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas las categorias", "Platillo", "Bebida", "Postre" }));
        cmbCategorias.addActionListener(this::cmbCategoriasActionPerformed);

        javax.swing.GroupLayout panelContenido1Layout = new javax.swing.GroupLayout(panelContenido1);
        panelContenido1.setLayout(panelContenido1Layout);
        panelContenido1Layout.setHorizontalGroup(
            panelContenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenido1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelContenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelContenido1Layout.createSequentialGroup()
                        .addComponent(lblITitulo1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(sep, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContenido1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelContenido1Layout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(cmbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );
        panelContenido1Layout.setVerticalGroup(
            panelContenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenido1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblITitulo1)
                .addGap(18, 18, 18)
                .addComponent(sep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(panelContenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSeleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49))
        );

        PanelPrincipal.add(panelContenido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        panelContenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        int fila = this.tblProductos.getSelectedRow();
        
        if (fila < 0) {
            JOptionPane.showMessageDialog(this,
                    "Selecciona un producto primero",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return; 
        }
        
        seleccionarProductoTabla();
        this.dispose();
        
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        String textoBusqueda = this.txtNombre.getText().trim();
        if(textoBusqueda.isEmpty() || textoBusqueda.equals("Buscar por nombre")){
            textoBusqueda = null;
        }
        
        int indexCategoria = this.cmbCategorias.getSelectedIndex();
        TipoProducto tipo = null;
        if (indexCategoria == 1) tipo = TipoProducto.PLATILLO;
        else if (indexCategoria == 2) tipo = TipoProducto.BEBIDA;
        else if (indexCategoria == 3) tipo = TipoProducto.POSTRE;
        
        try {
            Listproductos = controlador.consultarProductosFiltro(textoBusqueda, tipo);
            cargarProductos(Listproductos);
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmbCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriasActionPerformed
        if(this.cmbCategorias.getSelectedIndex() == 0){
            try {
                Listproductos = controlador.consultarProductos();
                cargarProductos(Listproductos);
            } catch (NegocioException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        }
        if(this.cmbCategorias.getSelectedIndex() == 1){
            try {
                Listproductos = controlador.consultarProductosFiltro(null, TipoProducto.PLATILLO);
                cargarProductos(Listproductos);
            } catch (NegocioException ex) {
               JOptionPane.showMessageDialog(this, ex.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        }
        if(this.cmbCategorias.getSelectedIndex() == 2){
            try {
                Listproductos = controlador.consultarProductosFiltro(null, TipoProducto.BEBIDA);
                cargarProductos(Listproductos);
            } catch (NegocioException ex) {
               JOptionPane.showMessageDialog(this, ex.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        }
        if(this.cmbCategorias.getSelectedIndex() == 3){
            try {
                Listproductos = controlador.consultarProductosFiltro(null, TipoProducto.POSTRE);
                cargarProductos(Listproductos);
            } catch (NegocioException ex) {
               JOptionPane.showMessageDialog(this, ex.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_cmbCategoriasActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        
    }//GEN-LAST:event_txtNombreActionPerformed

    public void inicializarTabla(){
    
        String[] columnas = {"Nombre","Tipo","Precio","Estado","Imagen"};
        
        DefaultTableModel modelo = new DefaultTableModel(columnas,0){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
            @Override
            public Class<?> getColumnClass(int columnIndex) { 
                return switch (columnIndex) {
                    case 0 -> String.class;    
                    case 1 -> Object.class;    
                    case 2 -> Float.class;     
                    case 3 -> String.class;    
                    case 4 -> ImageIcon.class; 
                    default -> Object.class;
                };
            }
        };
        tblProductos.setModel(modelo);
        tblProductos.getTableHeader().setReorderingAllowed(false);
        tblProductos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblProductos.setRowSelectionAllowed(true);
    
        utilerias.estilizarTablaProductos(tblProductos); 
        
        tblProductos.setRowHeight(100);
        
        try{
            List<ProductoDTO> listaProductos = controlador.consultarProductos();
            cargarProductos(listaProductos);
        }catch(NegocioException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void cargarProductos(List<ProductoDTO> productos) {
    DefaultTableModel modelo = (DefaultTableModel) this.tblProductos.getModel();

    modelo.setRowCount(0);

    for (ProductoDTO p : productos) {
        modelo.addRow(new Object[]{
            p.getNombre(),
            p.getTipoProducto(),
            p.getPrecio(),
            p.getEstado(), 
            convertirImagen(p.getImagen()) 
        });
      }
        this.Listproductos = productos;
        
    }
    
    private void seleccionarProductoTabla(){
        int fila = this.tblProductos.getSelectedRow();
        if(fila >= 0){
            this.productoSeleccionado = this.Listproductos.get(fila);
        }
    }

    public ProductoDTO getProductoSeleccionado() {
        return productoSeleccionado;
    }
    
    
    
    private ImageIcon convertirImagen(byte[] imagenBytes) {
        ImageIcon icono;
        if (imagenBytes == null) {
            icono = new ImageIcon("src/main/java/org/itson/restaurante/recursos/placeHolderProductoSinSubir.png");
        } else {
            icono = new ImageIcon(imagenBytes);
        }
        Image imgEscalada = icono.getImage().getScaledInstance(180, 130, Image.SCALE_SMOOTH);
        return new ImageIcon(imgEscalada);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    private PanelHeader panelHeader;
    private PanelMenu panelMenu;
    private PanelNavegacionPantallasPrincipales panelNavegacion;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JComboBox<String> cmbCategorias;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblITitulo1;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelContenido1;
    private javax.swing.JSeparator sep;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
