/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.restaurante.presentacion;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import org.itson.restaurante.utilerias.utilerias;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.itson.restaurante.dtos.IngredienteDTO;
import org.itson.restaurante.dtos.NuevoIngredienteDTO;
import org.itson.restaurante.dtos.UnidadMedidaDTO;
import org.itson.restaurante.negocio.NegocioException;
import org.itson.restaurante.utilerias.PanelHeader;
import org.itson.restaurante.utilerias.PanelNavegacionPantallasPrincipales;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author joset
 */
public class PantallaFormularioIngrediente extends javax.swing.JFrame {
    private IngredienteDTO ingredienteForm = null;
    private byte[] imagen;

    /**
     * Creates new form PantallaFormularioCliente
     */
    public PantallaFormularioIngrediente() {
        initComponents();
        
        utilerias.aplicarIcono(this);
        panelHeader = new PanelHeader();
        panelNavegacion = new PanelNavegacionPantallasPrincipales();

        panPrincipal.add(panelHeader, new AbsoluteConstraints(0, 0, 1366, 130));
        panPrincipal.add(panelNavegacion, new AbsoluteConstraints(0, 130, 1366, 45));

        panelNavegacion.setPantallasNavegacion("Ingredientes", "Formulario");

        utilerias.estilizarBotonPrimario(btnEditarIngrediente);

        utilerias.estilizarBotonPrimario(btnGuardarIngrediente);

        utilerias.estilizarBotonSinFondo(btnCancelar);
        
        utilerias.estilizarBotonPrimario(btnExaminarImagen);

        btnGuardarIngrediente.setVisible(true);
        btnEditarIngrediente.setVisible(false);
        cboUnidadMedida.removeAllItems();
        cboUnidadMedida.addItem(UnidadMedidaDTO.PIEZAS);
        cboUnidadMedida.addItem(UnidadMedidaDTO.GRAMOS);
        cboUnidadMedida.addItem(UnidadMedidaDTO.MILILITROS);

        this.setLocationRelativeTo(null);

    }

    public PantallaFormularioIngrediente(IngredienteDTO ingrediente) {
        initComponents();

        panelHeader = new PanelHeader();
        panelNavegacion = new PanelNavegacionPantallasPrincipales();

        panPrincipal.add(panelHeader, new AbsoluteConstraints(0, 0, 1366, 130));
        panPrincipal.add(panelNavegacion, new AbsoluteConstraints(0, 130, 1366, 45));

        panelNavegacion.setPantallasNavegacion("Clientes Frecuentes", "Formulario");

        utilerias.estilizarBotonPrimario(btnEditarIngrediente);

        utilerias.estilizarBotonPrimario(btnGuardarIngrediente);

        utilerias.estilizarBotonSinFondo(btnCancelar);
        
        utilerias.estilizarBotonPrimario(btnExaminarImagen);

        btnGuardarIngrediente.setVisible(false);
        btnEditarIngrediente.setVisible(true);
        cboUnidadMedida.removeAllItems();
        cboUnidadMedida.addItem(UnidadMedidaDTO.PIEZAS);
        cboUnidadMedida.addItem(UnidadMedidaDTO.GRAMOS);
        cboUnidadMedida.addItem(UnidadMedidaDTO.MILILITROS);
        
        this.setLocationRelativeTo(null);

        this.ingredienteForm = ingrediente;

        llenarCampos(this.ingredienteForm);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        lblPantalla = new javax.swing.JLabel();
        sep = new javax.swing.JSeparator();
        txtStock = new javax.swing.JTextField();
        lblStock = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblImagen = new javax.swing.JLabel();
        txtImagenSeleccionada = new javax.swing.JTextField();
        panContenido = new javax.swing.JPanel();
        cboUnidadMedida = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnExaminarImagen = new javax.swing.JButton();
        lblImagenSeleccionada = new javax.swing.JLabel();
        btnGuardarIngrediente = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEditarIngrediente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario Ingrediente");
        setSize(new java.awt.Dimension(1366, 768));

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panPrincipal.setMaximumSize(new java.awt.Dimension(1366, 768));
        panPrincipal.setPreferredSize(new java.awt.Dimension(1366, 768));
        panPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPantalla.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        lblPantalla.setText("Formulario Ingrediente");
        panPrincipal.add(lblPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        sep.setForeground(new java.awt.Color(18, 44, 79));
        panPrincipal.add(sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 1060, 10));
        panPrincipal.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, 300, 30));

        lblStock.setText("stock");
        panPrincipal.add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, -1, -1));

        lblNombre.setText("Nombre  *");
        panPrincipal.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        panPrincipal.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 300, 30));

        lblImagen.setText("imagen (opcional)");
        panPrincipal.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        txtImagenSeleccionada.setToolTipText("");
        panPrincipal.add(txtImagenSeleccionada, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 210, 30));

        panContenido.setBackground(new java.awt.Color(255, 255, 255));

        cboUnidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboUnidadMedidaActionPerformed(evt);
            }
        });

        jLabel1.setText("Unidad de medida");

        btnExaminarImagen.setBackground(new java.awt.Color(18, 44, 79));
        btnExaminarImagen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExaminarImagen.setForeground(new java.awt.Color(255, 255, 255));
        btnExaminarImagen.setText("Examinar");
        btnExaminarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExaminarImagenActionPerformed(evt);
            }
        });

        lblImagenSeleccionada.setMaximumSize(new java.awt.Dimension(360, 240));
        lblImagenSeleccionada.setMinimumSize(new java.awt.Dimension(306, 221));
        lblImagenSeleccionada.setPreferredSize(new java.awt.Dimension(306, 221));

        btnGuardarIngrediente.setBackground(new java.awt.Color(18, 44, 79));
        btnGuardarIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnGuardarIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarIngrediente.setText("Guardar Ingrediente");
        btnGuardarIngrediente.setToolTipText("");
        btnGuardarIngrediente.setMaximumSize(new java.awt.Dimension(149, 32));
        btnGuardarIngrediente.setMinimumSize(new java.awt.Dimension(149, 32));
        btnGuardarIngrediente.setPreferredSize(new java.awt.Dimension(149, 32));
        btnGuardarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarIngredienteActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(18, 44, 79));
        btnCancelar.setText("Cancelar ");
        btnCancelar.setOpaque(true);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnEditarIngrediente.setBackground(new java.awt.Color(18, 44, 79));
        btnEditarIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnEditarIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarIngrediente.setText("Editar Ingrediente");
        btnEditarIngrediente.setToolTipText("");
        btnEditarIngrediente.setMaximumSize(new java.awt.Dimension(133, 32));
        btnEditarIngrediente.setMinimumSize(new java.awt.Dimension(133, 32));
        btnEditarIngrediente.setPreferredSize(new java.awt.Dimension(133, 32));
        btnEditarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarIngredienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panContenidoLayout = new javax.swing.GroupLayout(panContenido);
        panContenido.setLayout(panContenidoLayout);
        panContenidoLayout.setHorizontalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panContenidoLayout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addGroup(panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panContenidoLayout.createSequentialGroup()
                        .addComponent(btnEditarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220)
                        .addComponent(btnGuardarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panContenidoLayout.createSequentialGroup()
                        .addGroup(panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panContenidoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnExaminarImagen))
                            .addComponent(lblImagenSeleccionada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(197, 197, 197)
                        .addGroup(panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cboUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(477, 477, 477))))
        );
        panContenidoLayout.setVerticalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panContenidoLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExaminarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(lblImagenSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        panPrincipal.add(panContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 177, 1370, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1364, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        ingredienteForm = null;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarIngredienteActionPerformed
        String nombre = txtNombre.getText().trim();
        String stockStr = txtStock.getText().trim();
        UnidadMedidaDTO unidadMedida = UnidadMedidaDTO.values()[cboUnidadMedida.getSelectedIndex()];

        if (nombre.isEmpty() || stockStr.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Nombre y stock  son obligatorios",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Integer stock = Integer.valueOf(stockStr);

            NuevoIngredienteDTO nuevoIngrediente = new NuevoIngredienteDTO(
                nombre,
                unidadMedida,
                stock,
                this.imagen 
            );

            Controlador.getIntancia().registrarIngrediente(nuevoIngrediente);

            JOptionPane.showMessageDialog(this,
                "Ingrediente guardado correctamente",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);

            this.dispose();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                "El stock debe ser un número entero",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarIngredienteActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnEditarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarIngredienteActionPerformed
        String nombre = txtNombre.getText().trim();
        String stockStr = txtStock.getText().trim();

        if (nombre.isEmpty() || stockStr.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Nombre y stock son obligatorios",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Integer stock = Integer.valueOf(stockStr);
            
            byte[] imagenAct;
            if (this.imagen != null) {
                imagenAct = this.imagen; //si se cambio la imagen
            } else {
                imagenAct = ingredienteForm.getImagen(); //si no se usa la original
            }
            IngredienteDTO ingredienteActualizado = new IngredienteDTO(
                ingredienteForm.getId(),
                nombre,
                ingredienteForm.getUnidadMedida(),
                stock,
                imagenAct    
            );

            Controlador.getIntancia().actualizarIngrediente(ingredienteActualizado);

            JOptionPane.showMessageDialog(this,
                "Ingrediente actualizado correctamente",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);

            this.dispose();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                "El stock debe ser un número entero",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_btnEditarIngredienteActionPerformed

    private void btnExaminarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExaminarImagenActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
                "Imágenes", "jpg", "jpeg", "png", "gif"
        ));

        int resultado = fileChooser.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            txtImagenSeleccionada.setText(archivo.getAbsolutePath());

            try {
                imagen = java.nio.file.Files.readAllBytes(archivo.toPath());
                // mostrar preview
                ImageIcon icono = new ImageIcon(imagen);
                Image escalada = icono.getImage().getScaledInstance(306, 221, Image.SCALE_SMOOTH);
                lblImagenSeleccionada.setIcon(new ImageIcon(escalada));
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error al cargar la imagen");
            }
        }
    }//GEN-LAST:event_btnExaminarImagenActionPerformed

    private void cboUnidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboUnidadMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboUnidadMedidaActionPerformed

    public IngredienteDTO getIngredienteDTO() {
        return ingredienteForm;
    }

    private void llenarCampos(IngredienteDTO ingrediente) {
        txtNombre.setText(ingrediente.getNombre());
        txtStock.setText(String.valueOf(ingrediente.getStock()));
        cboUnidadMedida.setSelectedItem(ingrediente.getUnidadMedida());
        cboUnidadMedida.setEnabled(false);

        if (ingrediente.getImagen() != null) {
            ImageIcon icono = new ImageIcon(ingrediente.getImagen());
            Image escalada = icono.getImage().getScaledInstance(306, 221, Image.SCALE_SMOOTH);
            lblImagenSeleccionada.setIcon(new ImageIcon(escalada));
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditarIngrediente;
    private javax.swing.JButton btnExaminarImagen;
    private javax.swing.JButton btnGuardarIngrediente;
    private javax.swing.JComboBox<UnidadMedidaDTO> cboUnidadMedida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblImagenSeleccionada;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPantalla;
    private javax.swing.JLabel lblStock;
    private javax.swing.JPanel panContenido;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JSeparator sep;
    private javax.swing.JTextField txtImagenSeleccionada;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
    private org.itson.restaurante.utilerias.PanelHeader panelHeader;
    private org.itson.restaurante.utilerias.PanelNavegacionPantallasPrincipales panelNavegacion;
}
