/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.restaurante.presentacion;

import org.itson.restaurante.dtos.RolEmpleado;
import org.itson.restaurante.utilerias.PanelBordeRedondo;
import org.itson.restaurante.utilerias.utilerias;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JSeparator;
import org.itson.restaurante.utilerias.PanelHeader;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author joset
 */
public class PantallaLogin extends javax.swing.JFrame {

    /**
     * Creates new form PantallaLogin
     */
    public PantallaLogin() {
        initComponents();
        utilerias.aplicarIcono(this);
        
        //paneles reutilizables
        panelHeader = new PanelHeader();

        panPrincipal.add(panelHeader, new AbsoluteConstraints(0, 0, 1020, 768));
        panSecundario.setLayout(new AbsoluteLayout());

        PanelBordeRedondo panelCentral = new PanelBordeRedondo(30, new Color(251, 249, 228));
        panelCentral.setLayout(new AbsoluteLayout());

        JLabel lblTitulo = new JLabel("¿Cómo deseas ingresar?");
        lblTitulo.setFont(new Font("Segoe UI", Font.BOLD, 22));
        lblTitulo.setForeground(new Color(18, 44, 79));
        lblTitulo.setHorizontalAlignment(JLabel.CENTER);

        JLabel lblSubtitulo = new JLabel("<html><center>Selecciona tu rol para acceder<br>con los permisos correspondientes</center></html>");
        lblSubtitulo.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        lblSubtitulo.setForeground(new Color(91, 136, 178));
        lblSubtitulo.setHorizontalAlignment(JLabel.CENTER);

        JSeparator sep = new JSeparator();
        sep.setForeground(new Color(18, 44, 79));

        JButton btnMesero = new JButton("Soy Mesero");
        btnMesero.setBackground(new Color(18, 44, 79));
        btnMesero.setForeground(Color.WHITE);
        utilerias.estilizarBotonPrimario(btnMesero);
        btnMesero.setFont(new Font("Segoe UI", Font.BOLD, 16));

        JButton btnAdmin = new JButton("Soy Administrador");
        btnAdmin.setFont(new Font("Segoe UI", Font.BOLD, 16));
        utilerias.estilizarBotonSinFondo(btnAdmin);

        btnMesero.addActionListener(e -> {
            Controlador.getIntancia().setRolActual(RolEmpleado.MESERO);
            Controlador.getIntancia().abrirComandas(this);
        });
        btnAdmin.addActionListener(e -> {
            Controlador.getIntancia().setRolActual(RolEmpleado.ADMINISTRADOR);
            Controlador.getIntancia().abrirMenuPrincipal(this);
        });

        panelCentral.add(lblTitulo,    new AbsoluteConstraints(50, 80, 340,  40));
        panelCentral.add(lblSubtitulo, new AbsoluteConstraints(40, 130, 360,  50));
        panelCentral.add(sep,          new AbsoluteConstraints(40, 190, 360,  10));
        panelCentral.add(btnMesero,    new AbsoluteConstraints(50, 220, 340,  55));
        panelCentral.add(btnAdmin,     new AbsoluteConstraints(50, 295, 340,  55));

        panSecundario.add(panelCentral, new AbsoluteConstraints(290, 57, 440, 525));

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        panSecundario = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(18, 44, 79));
        setMinimumSize(new java.awt.Dimension(1000, 768));
        setPreferredSize(new java.awt.Dimension(1000, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panPrincipal.setBackground(new java.awt.Color(18, 44, 79));
        panPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(91, 136, 178)));
        panPrincipal.setAlignmentX(0.0F);
        panPrincipal.setAlignmentY(0.0F);
        panPrincipal.setMaximumSize(new java.awt.Dimension(1000, 768));
        panPrincipal.setMinimumSize(new java.awt.Dimension(1000, 768));
        panPrincipal.setName(""); // NOI18N
        panPrincipal.setPreferredSize(new java.awt.Dimension(1000, 768));
        panPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 130));

        panSecundario.setBackground(new java.awt.Color(18, 44, 79));
        panSecundario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(91, 136, 178), 4));

        javax.swing.GroupLayout panSecundarioLayout = new javax.swing.GroupLayout(panSecundario);
        panSecundario.setLayout(panSecundarioLayout);
        panSecundarioLayout.setHorizontalGroup(
            panSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        panSecundarioLayout.setVerticalGroup(
            panSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );

        getContentPane().add(panSecundario, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 130, 1020, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JPanel panSecundario;
    // End of variables declaration//GEN-END:variables
    private org.itson.restaurante.utilerias.PanelHeader panelHeader;

}
