package org.itson.restaurante.presentacion;

import org.itson.restaurante.dtos.ClienteFrecuenteDTO;
import org.itson.restaurante.utilerias.utilerias;
import javax.swing.SwingUtilities;
import org.itson.restaurante.dtos.IngredienteDTO;
import org.itson.restaurante.utilerias.PanelHeader;
import org.itson.restaurante.utilerias.PanelMenu;
import org.itson.restaurante.utilerias.PanelNavegacionPantallasPrincipales;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author joset
 */
public class PantallaIngredientes extends javax.swing.JFrame {

    /**
     * Creates new form PantallaCliente
     */
    public PantallaIngredientes() {
        initComponents();
        //paneles reutilizables
        panelHeader = new PanelHeader();
        panelMenu = new PanelMenu();
        panelNavegacion = new PanelNavegacionPantallasPrincipales();

        panPrincipal.add(panelHeader, new AbsoluteConstraints(0, 0, 1366, 130));
        panPrincipal.add(panelMenu, new AbsoluteConstraints(0, 130, 215, 640));
        panPrincipal.add(panelNavegacion, new AbsoluteConstraints(215, 130, 1151, 45));

        panelNavegacion.setPantallasNavegacion("Ingredientes", "Menu Ingredientes");

        utilerias.estilizarBotonPrimario(btnEditarIngrediente);

        utilerias.estilizarBotonPrimario(btnNuevoIngrediente);

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        lblPrincipal1 = new javax.swing.JLabel();
        sep = new javax.swing.JSeparator();
        btnNuevoIngrediente = new javax.swing.JButton();
        btnEditarIngrediente = new javax.swing.JButton();
        panContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Clientes Menu");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panPrincipal.setMaximumSize(new java.awt.Dimension(1366, 768));
        panPrincipal.setPreferredSize(new java.awt.Dimension(1366, 768));
        panPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPrincipal1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        lblPrincipal1.setText("Menu Ingredientes");
        panPrincipal.add(lblPrincipal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        sep.setForeground(new java.awt.Color(18, 44, 79));
        panPrincipal.add(sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 1080, -1));

        btnNuevoIngrediente.setBackground(new java.awt.Color(18, 44, 79));
        btnNuevoIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNuevoIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoIngrediente.setText("Nuevo Ingrediente");
        btnNuevoIngrediente.setToolTipText("");
        btnNuevoIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoIngredienteActionPerformed(evt);
            }
        });
        panPrincipal.add(btnNuevoIngrediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 240, -1));

        btnEditarIngrediente.setBackground(new java.awt.Color(18, 44, 79));
        btnEditarIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditarIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarIngrediente.setText("Editar Ingrediente");
        btnEditarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarIngredienteActionPerformed(evt);
            }
        });
        panPrincipal.add(btnEditarIngrediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 280, 230, -1));

        panContenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panContenidoLayout = new javax.swing.GroupLayout(panContenido);
        panContenido.setLayout(panContenidoLayout);
        panContenidoLayout.setHorizontalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );
        panContenidoLayout.setVerticalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        panPrincipal.add(panContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 1150, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoIngredienteActionPerformed

        Controlador.getIntancia().abrirFomularioIngrediente(this);
    }//GEN-LAST:event_btnNuevoIngredienteActionPerformed

    private void btnEditarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarIngredienteActionPerformed
        PantallaBusquedaIngrediente dialogo = new PantallaBusquedaIngrediente((java.awt.Frame) SwingUtilities.getWindowAncestor(this), true);
        dialogo.setVisible(true);

        IngredienteDTO ingrediente = dialogo.getIngredienteSeleccionado();

        if (ingrediente != null) {
            Controlador.getIntancia().abrirFormularioEditarIngrediente(ingrediente, this);
        }
    }//GEN-LAST:event_btnEditarIngredienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarIngrediente;
    private javax.swing.JButton btnNuevoIngrediente;
    private javax.swing.JLabel lblPrincipal1;
    private javax.swing.JPanel panContenido;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JSeparator sep;
    // End of variables declaration//GEN-END:variables
    private org.itson.restaurante.utilerias.PanelHeader panelHeader;
    private org.itson.restaurante.utilerias.PanelMenu panelMenu;
    private org.itson.restaurante.utilerias.PanelNavegacionPantallasPrincipales panelNavegacion;
}
