/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.utilerias;

import com.mycompany.restaurantepresentacion.Controlador;

/**
 *
 * @author joset
 */
public class PanelMenu extends javax.swing.JPanel {

    private Controlador controlador = Controlador.getIntancia();

    /**
     * Creates new form PanelMenu
     */
    public PanelMenu() {
        initComponents();

        utilerias.estilizarBotonMenu(btnInicio);

        utilerias.estilizarBotonMenu(btnIngredientes);

        utilerias.estilizarBotonMenu(btnProductos);

        utilerias.estilizarBotonMenu(btnComandas);

        utilerias.estilizarBotonMenu(btnReportes);
        
        configurarSegunRol();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panNavegacion = new javax.swing.JPanel();
        lblPrincipal = new javax.swing.JLabel();
        lblOperacion = new javax.swing.JLabel();
        lblCatalogo = new javax.swing.JLabel();
        lblAnalisis = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnIngredientes = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnComandas = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();

        panNavegacion.setBackground(new java.awt.Color(18, 44, 79));
        panNavegacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panNavegacion.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        lblPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPrincipal.setForeground(new java.awt.Color(204, 204, 204));
        lblPrincipal.setText("PRINCIPAL");

        lblOperacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblOperacion.setForeground(new java.awt.Color(204, 204, 204));
        lblOperacion.setText("OPERACIÓN");

        lblCatalogo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCatalogo.setForeground(new java.awt.Color(204, 204, 204));
        lblCatalogo.setText("CATÁLOGOS");

        lblAnalisis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAnalisis.setForeground(new java.awt.Color(204, 204, 204));
        lblAnalisis.setText("ANÁLISIS");

        btnInicio.setBackground(new java.awt.Color(18, 44, 79));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Inicio");
        btnInicio.setBorder(null);
        btnInicio.setBorderPainted(false);
        btnInicio.setFocusPainted(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnIngredientes.setBackground(new java.awt.Color(18, 44, 79));
        btnIngredientes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnIngredientes.setForeground(new java.awt.Color(255, 255, 255));
        btnIngredientes.setText("Ingredientes");
        btnIngredientes.setBorder(null);
        btnIngredientes.setBorderPainted(false);
        btnIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngredientesActionPerformed(evt);
            }
        });

        btnClientes.setBackground(new java.awt.Color(17, 50, 93));
        btnClientes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setText("Clientes");
        btnClientes.setBorder(null);
        btnClientes.setBorderPainted(false);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnProductos.setBackground(new java.awt.Color(18, 44, 79));
        btnProductos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnProductos.setText("Productos");
        btnProductos.setBorder(null);
        btnProductos.setBorderPainted(false);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnComandas.setBackground(new java.awt.Color(18, 44, 79));
        btnComandas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnComandas.setForeground(new java.awt.Color(255, 255, 255));
        btnComandas.setText("Comandas");
        btnComandas.setToolTipText("");
        btnComandas.setBorder(null);
        btnComandas.setBorderPainted(false);
        btnComandas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComandasActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(18, 44, 79));
        btnReportes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Reportes");
        btnReportes.setToolTipText("");
        btnReportes.setBorder(null);
        btnReportes.setBorderPainted(false);
        btnReportes.setDefaultCapable(false);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panNavegacionLayout = new javax.swing.GroupLayout(panNavegacion);
        panNavegacion.setLayout(panNavegacionLayout);
        panNavegacionLayout.setHorizontalGroup(
            panNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnReportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panNavegacionLayout.createSequentialGroup()
                .addGroup(panNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnComandas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIngredientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(btnInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panNavegacionLayout.createSequentialGroup()
                        .addGroup(panNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panNavegacionLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(lblAnalisis))
                            .addGroup(panNavegacionLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lblOperacion))
                            .addGroup(panNavegacionLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(lblPrincipal))
                            .addGroup(panNavegacionLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lblCatalogo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panNavegacionLayout.setVerticalGroup(
            panNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNavegacionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblPrincipal)
                .addGap(12, 12, 12)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lblCatalogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lblOperacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnComandas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lblAnalisis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panNavegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panNavegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void configurarSegunRol() {
        if (Controlador.getIntancia().esMesero()) {
            btnInicio.setVisible(false);
            btnInicio.setVisible(false);
            btnIngredientes.setVisible(false);
            btnProductos.setVisible(false);
            btnClientes.setVisible(false);
            btnReportes.setVisible(false);
            lblCatalogo.setVisible(false);
            lblAnalisis.setVisible(false);
        }
    }
    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        controlador.abrirMenuPrincipal(
                (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this)
        );
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngredientesActionPerformed
        controlador.abrirIngredientes(
                (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this)
        );
    }//GEN-LAST:event_btnIngredientesActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        controlador.abrirClientes(
                (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this)
        );
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        controlador.abrirProductos(
                (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this)
        );
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnComandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComandasActionPerformed
        controlador.abrirComandas(
                (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this)
        );
    }//GEN-LAST:event_btnComandasActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        controlador.abrirReportes(
                (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this)
        );
    }//GEN-LAST:event_btnReportesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnComandas;
    private javax.swing.JButton btnIngredientes;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JLabel lblAnalisis;
    private javax.swing.JLabel lblCatalogo;
    private javax.swing.JLabel lblOperacion;
    private javax.swing.JLabel lblPrincipal;
    private javax.swing.JPanel panNavegacion;
    // End of variables declaration//GEN-END:variables
}
