/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.restaurantepresentacion;

import com.mycompany.restaurantedtos.NuevoClienteDTO;
import com.mycompany.utilerias.utilerias;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joset
 */
public class PantallaBusquedaClienteD extends javax.swing.JDialog {

    /**
     * Creates new form PantallaBusquedaClienteD
     */
    private NuevoClienteDTO clienteSeleccionado = null;
    private List<NuevoClienteDTO> listaClientes = new ArrayList<>();

    public PantallaBusquedaClienteD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();

        utilerias.colocarLogo(btnLogo);

        utilerias.estilizarBotonPrimario(btnCancelar);

        this.setLocationRelativeTo(null);

        inicializarTabla();

        this.txtBusqueda.setText("Buscar por nombre...");

        this.txtBusqueda.setForeground(Color.GRAY);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        panSuperior = new javax.swing.JPanel();
        btnLogo = new javax.swing.JButton();
        lblNombreRestaurante = new javax.swing.JLabel();
        panMostrarNavegacion = new javax.swing.JPanel();
        lblPantallaActualNav = new javax.swing.JLabel();
        lblNombreBtnPantalla = new javax.swing.JLabel();
        lblPrincipal1 = new javax.swing.JLabel();
        sep = new javax.swing.JSeparator();
        btnCancelar = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnBuscarCliente = new javax.swing.JButton();
        btnSeleccionarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panPrincipal.setMaximumSize(new java.awt.Dimension(1366, 768));
        panPrincipal.setPreferredSize(new java.awt.Dimension(1366, 768));
        panPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panSuperior.setBackground(new java.awt.Color(18, 44, 79));
        panSuperior.setLayout(new javax.swing.BoxLayout(panSuperior, javax.swing.BoxLayout.LINE_AXIS));

        btnLogo.setText("btnLogo");
        btnLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoActionPerformed(evt);
            }
        });
        panSuperior.add(btnLogo);

        lblNombreRestaurante.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombreRestaurante.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreRestaurante.setText("Nombre del restaurante");
        panSuperior.add(lblNombreRestaurante);

        panPrincipal.add(panSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 130));

        panMostrarNavegacion.setBackground(new java.awt.Color(91, 136, 178));

        lblPantallaActualNav.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblPantallaActualNav.setForeground(new java.awt.Color(255, 255, 255));
        lblPantallaActualNav.setText("Busqueda");

        lblNombreBtnPantalla.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblNombreBtnPantalla.setForeground(new java.awt.Color(18, 44, 79));
        lblNombreBtnPantalla.setText("Clientes Frecuentes >");

        javax.swing.GroupLayout panMostrarNavegacionLayout = new javax.swing.GroupLayout(panMostrarNavegacion);
        panMostrarNavegacion.setLayout(panMostrarNavegacionLayout);
        panMostrarNavegacionLayout.setHorizontalGroup(
            panMostrarNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMostrarNavegacionLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblNombreBtnPantalla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPantallaActualNav)
                .addContainerGap(1012, Short.MAX_VALUE))
        );
        panMostrarNavegacionLayout.setVerticalGroup(
            panMostrarNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMostrarNavegacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panMostrarNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreBtnPantalla)
                    .addComponent(lblPantallaActualNav))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panPrincipal.add(panMostrarNavegacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1370, -1));

        lblPrincipal1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        lblPrincipal1.setText("Busqueda Cliente");
        panPrincipal.add(lblPrincipal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        sep.setForeground(new java.awt.Color(18, 44, 79));
        panPrincipal.add(sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 243, 1060, 10));

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(18, 44, 79));
        btnCancelar.setText("Cancelar ");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panPrincipal.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 700, 190, -1));

        txtBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtBusqueda.setToolTipText("");
        txtBusqueda.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtBusqueda.setMinimumSize(new java.awt.Dimension(3, 32));
        txtBusqueda.setName(""); // NOI18N
        txtBusqueda.setPreferredSize(new java.awt.Dimension(3, 32));
        txtBusqueda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBusquedaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBusquedaFocusLost(evt);
            }
        });
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        panPrincipal.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 262, 850, -1));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        panPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 1060, 350));

        btnBuscarCliente.setBackground(new java.awt.Color(18, 44, 79));
        btnBuscarCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarCliente.setText("Buscar ");
        btnBuscarCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 44, 79), 2));
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });
        panPrincipal.add(btnBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 260, 190, -1));

        btnSeleccionarCliente.setBackground(new java.awt.Color(18, 44, 79));
        btnSeleccionarCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSeleccionarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarCliente.setText("Seleccionar");
        btnSeleccionarCliente.setToolTipText("");
        btnSeleccionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarClienteActionPerformed(evt);
            }
        });
        panPrincipal.add(btnSeleccionarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 700, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        clienteSeleccionado = null;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtBusquedaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBusquedaFocusGained
        if (this.txtBusqueda.getText().equals("Buscar por nombre...")) {

            this.txtBusqueda.setText("");

            this.txtBusqueda.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtBusquedaFocusGained

    private void txtBusquedaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBusquedaFocusLost
        if (this.txtBusqueda.getText().isEmpty()) {

            this.txtBusqueda.setText("Buscar por nombre...");

            this.txtBusqueda.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtBusquedaFocusLost

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        if (evt.getClickCount() == 2) {

            seleccionarClienteTabla();

        }
    }//GEN-LAST:event_tblClientesMouseClicked

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        String textoBusqueda = this.txtBusqueda.getText().trim();
        if (textoBusqueda.equals("Buscar por nombre...") || textoBusqueda.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Escribe un nombre para buscar",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        //TODO
        // SE DEBE LLAMAR A LA BO Y BUSCAR LOS CLIENTES POR EL NOMBRE y METERLO A UNA LISTA List<NuevoClienteDTO> resultados 
        // LUEGO cargarClientes(resultados);
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnSeleccionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarClienteActionPerformed
        if (tblClientes.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this,
                    "Selecciona un cliente primero",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        seleccionarClienteTabla();
    }//GEN-LAST:event_btnSeleccionarClienteActionPerformed

    public void inicializarTabla() {

        String[] columnas = {"Nombre", "Teléfono", "Correo", "Visitas", "Total gastado", "Puntos", "Últ. comanda"};//Columnas

        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {       // que no se pueda editar las celdas
                return false;
            }
        };

        this.tblClientes.setModel(modelo);

        this.tblClientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        this.tblClientes.setRowSelectionAllowed(true);
    }

    public void cargarClientes(List<NuevoClienteDTO> clientes) {

        DefaultTableModel modelo = (DefaultTableModel) this.tblClientes.getModel();

        modelo.setRowCount(0);

        for (NuevoClienteDTO c : clientes) {

            modelo.addRow(new Object[]{
                c.getNombre() + " " + c.getApellidoPaterno() + " " + c.getApellidoMaterno(),
                c.getTelefono(),
                c.getCorreo(),
                c.getVisitas(),
                "$" + String.format("%.2f", c.getTotalGastado()),
                c.getPuntos() + " pts",
                c.getUltimaComanda()

            });
        }

        this.listaClientes = clientes;
    }

    private void seleccionarClienteTabla() {

        int fila = this.tblClientes.getSelectedRow();

        if (fila >= 0) {

            this.clienteSeleccionado = this.listaClientes.get(fila);

        }
    }

    public NuevoClienteDTO getClienteSeleccionado() {
        return this.clienteSeleccionado;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaBusquedaClienteD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaBusquedaClienteD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaBusquedaClienteD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaBusquedaClienteD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PantallaBusquedaClienteD dialog = new PantallaBusquedaClienteD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLogo;
    private javax.swing.JButton btnSeleccionarCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombreBtnPantalla;
    private javax.swing.JLabel lblNombreRestaurante;
    private javax.swing.JLabel lblPantallaActualNav;
    private javax.swing.JLabel lblPrincipal1;
    private javax.swing.JPanel panMostrarNavegacion;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JPanel panSuperior;
    private javax.swing.JSeparator sep;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
