/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.restaurantepresentacion;

import com.mycompany.restaurantedtos.ClienteFrecuenteDTO;
import com.mycompany.utilerias.utilerias;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author joset
 */
public class PantallaFormularioCliente extends javax.swing.JFrame {

    private ClienteFrecuenteDTO clienteForm;

    /**
     * Creates new form PantallaFormularioCliente
     */
    public PantallaFormularioCliente() {
        initComponents();
        
        utilerias.colocarLogo(btnLogo);
        
        utilerias.estilizarBotonPrimario(btnEditarCliente);
        
        utilerias.estilizarBotonPrimario(btnGuardarCliente);
        
        utilerias.estilizarBotonSinFondo(btnCancelar);
        
        verificarBoton();
        
        txtFechaRegistro.setEditable(false);
        
        this.setLocationRelativeTo(null);        

    }

    public PantallaFormularioCliente(ClienteFrecuenteDTO cliente) {
        initComponents();
        
        utilerias.colocarLogo(btnLogo);
        
        utilerias.estilizarBotonPrimario(btnEditarCliente);
        
        utilerias.estilizarBotonPrimario(btnGuardarCliente);
        
        utilerias.estilizarBotonSinFondo(btnCancelar);
        
        verificarBoton();
        txtFechaRegistro.setEditable(false);
        
        this.setLocationRelativeTo(null);

        this.clienteForm = cliente;
        
        llenarCampos(this.clienteForm);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        panSuperior = new javax.swing.JPanel();
        btnLogo = new javax.swing.JButton();
        lblNombreRestaurante = new javax.swing.JLabel();
        panMostrarNavegacion = new javax.swing.JPanel();
        lblPantallaActualNav = new javax.swing.JLabel();
        lblNombreBtnPantalla = new javax.swing.JLabel();
        lblPantalla = new javax.swing.JLabel();
        sep = new javax.swing.JSeparator();
        btnCancelar = new javax.swing.JButton();
        btnGuardarCliente = new javax.swing.JButton();
        txtApellidoP = new javax.swing.JTextField();
        txtFechaRegistro = new javax.swing.JTextField();
        lblApellidoPaterno = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblFecharRegistro = new javax.swing.JLabel();
        txtCorreoElectronico = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        lblApellidoMaterno = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JTextField();
        lblTelefonod = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnEditarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario Cliente");
        setSize(new java.awt.Dimension(1366, 768));

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panPrincipal.setMaximumSize(new java.awt.Dimension(1366, 768));
        panPrincipal.setPreferredSize(new java.awt.Dimension(1366, 768));
        panPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panSuperior.setBackground(new java.awt.Color(18, 44, 79));
        panSuperior.setLayout(new javax.swing.BoxLayout(panSuperior, javax.swing.BoxLayout.LINE_AXIS));

        btnLogo.setText("btnLogo");
        btnLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoActionPerformed(evt);
            }
        });
        panSuperior.add(btnLogo);

        lblNombreRestaurante.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombreRestaurante.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreRestaurante.setText("Nombre del restaurante");
        panSuperior.add(lblNombreRestaurante);

        panPrincipal.add(panSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 130));

        panMostrarNavegacion.setBackground(new java.awt.Color(91, 136, 178));

        lblPantallaActualNav.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblPantallaActualNav.setForeground(new java.awt.Color(255, 255, 255));
        lblPantallaActualNav.setText("Formulario cliente");

        lblNombreBtnPantalla.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblNombreBtnPantalla.setForeground(new java.awt.Color(18, 44, 79));
        lblNombreBtnPantalla.setText("Clientes Frecuentes >");

        javax.swing.GroupLayout panMostrarNavegacionLayout = new javax.swing.GroupLayout(panMostrarNavegacion);
        panMostrarNavegacion.setLayout(panMostrarNavegacionLayout);
        panMostrarNavegacionLayout.setHorizontalGroup(
            panMostrarNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMostrarNavegacionLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblNombreBtnPantalla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPantallaActualNav)
                .addContainerGap(931, Short.MAX_VALUE))
        );
        panMostrarNavegacionLayout.setVerticalGroup(
            panMostrarNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMostrarNavegacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panMostrarNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreBtnPantalla)
                    .addComponent(lblPantallaActualNav))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panPrincipal.add(panMostrarNavegacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1370, -1));

        lblPantalla.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        lblPantalla.setText("Formulario Cliente");
        panPrincipal.add(lblPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        sep.setForeground(new java.awt.Color(18, 44, 79));
        panPrincipal.add(sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 1060, 10));

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(18, 44, 79));
        btnCancelar.setText("Cancelar ");
        btnCancelar.setOpaque(true);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panPrincipal.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 550, 190, 30));

        btnGuardarCliente.setBackground(new java.awt.Color(18, 44, 79));
        btnGuardarCliente.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnGuardarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarCliente.setText("Guardar Cliente");
        btnGuardarCliente.setToolTipText("");
        btnGuardarCliente.setMaximumSize(new java.awt.Dimension(149, 32));
        btnGuardarCliente.setMinimumSize(new java.awt.Dimension(149, 32));
        btnGuardarCliente.setPreferredSize(new java.awt.Dimension(149, 32));
        btnGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarClienteActionPerformed(evt);
            }
        });
        panPrincipal.add(btnGuardarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 550, 190, 30));
        panPrincipal.add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, 300, 30));

        txtFechaRegistro.setName(""); // NOI18N
        txtFechaRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFechaRegistroMouseClicked(evt);
            }
        });
        txtFechaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaRegistroActionPerformed(evt);
            }
        });
        panPrincipal.add(txtFechaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 470, 300, 30));

        lblApellidoPaterno.setText("Apellido Paterno *");
        panPrincipal.add(lblApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, -1, -1));

        lblNombres.setText("Nombres  *");
        panPrincipal.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        panPrincipal.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 300, 30));

        lblFecharRegistro.setText("Fecha de registro");
        panPrincipal.add(lblFecharRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, -1, -1));
        panPrincipal.add(txtCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 300, 30));

        lblCorreo.setText("Correo electronico (opcional)");
        panPrincipal.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, -1, -1));

        lblApellidoMaterno.setText("Apellido Materno *");
        panPrincipal.add(lblApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        txtApellidoMaterno.setToolTipText("");
        panPrincipal.add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 300, 30));

        lblTelefonod.setText("Teléfono *");
        panPrincipal.add(lblTelefonod, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, -1, -1));
        panPrincipal.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, 300, 30));

        btnEditarCliente.setBackground(new java.awt.Color(18, 44, 79));
        btnEditarCliente.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnEditarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarCliente.setText("Editar Cliente");
        btnEditarCliente.setToolTipText("");
        btnEditarCliente.setMaximumSize(new java.awt.Dimension(133, 32));
        btnEditarCliente.setMinimumSize(new java.awt.Dimension(133, 32));
        btnEditarCliente.setPreferredSize(new java.awt.Dimension(133, 32));
        btnEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClienteActionPerformed(evt);
            }
        });
        panPrincipal.add(btnEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 550, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        clienteForm = null;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClienteActionPerformed
        String nombre = txtNombres.getText().trim();
        
        String apellidoP = txtApellidoP.getText().trim();
        
        String apellidoM = txtApellidoMaterno.getText().trim();
        
        String telefono = txtTelefono.getText().trim();
        
        String correo = txtCorreoElectronico.getText().trim();
        

        // validacion de los campos vacios
        if (nombre.isEmpty() || apellidoP.isEmpty() || apellidoM.isEmpty() || telefono.isEmpty()) {
            
            JOptionPane.showMessageDialog(this,
                    "Ningún campo puede estar vacío",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
            
        }
        ClienteFrecuenteDTO nuevoCliente = new ClienteFrecuenteDTO(
                nombre, apellidoP, apellidoM, telefono, correo, LocalDate.now(), clienteForm.getNumeroVisitas(), clienteForm.getTotalGastado(), clienteForm.getPuntosAcumulados());
        
        //TODO
        // clienteBO.registrarCliente(nuevoCliente);
        
        this.clienteForm = nuevoCliente;
        
        JOptionPane.showMessageDialog(this,
                "Cliente guardado correctamente",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);
        

        this.dispose(); // cierra esta y lanza el windowClosed
        
    }//GEN-LAST:event_btnGuardarClienteActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void btnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteActionPerformed
        String nombre = txtNombres.getText().trim();
        
        String apellidoP = txtApellidoP.getText().trim();
        
        String apellidoM = txtApellidoMaterno.getText().trim();
        
        String telefono = txtTelefono.getText().trim();
        
        String correo = txtCorreoElectronico.getText().trim();
        
        LocalDate fechaRegistro = clienteForm.getFechaRegistro();
        
        // validacion de los campos vacios
        if (nombre.isEmpty() || apellidoP.isEmpty() || apellidoM.isEmpty() || telefono.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Ningún campo puede estar vacío",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            
        }
        ClienteFrecuenteDTO clienteActualizado = new ClienteFrecuenteDTO(
                clienteForm.getId(),nombre, apellidoP, apellidoM, telefono, correo, fechaRegistro, clienteForm.getNumeroVisitas(),
                clienteForm.getTotalGastado(), clienteForm.getPuntosAcumulados());
        
        //TODO
        // clienteBO.actualizarCliente(clienteActualizado);
        
        this.clienteForm = clienteActualizado;
        
        JOptionPane.showMessageDialog(this,
                "Cliente actualizado correctamente",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);

        this.dispose(); // cierra y lanza el windowClosed
    }//GEN-LAST:event_btnEditarClienteActionPerformed

    private void txtFechaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaRegistroActionPerformed

    private void txtFechaRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaRegistroMouseClicked
        txtFechaRegistro.setText(
                LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yy")));
    }//GEN-LAST:event_txtFechaRegistroMouseClicked

    public ClienteFrecuenteDTO getClienteFrecuenteDTO() {
        return clienteForm;
    }

    public void verificarBoton() {
        if (txtNombres.getText().isEmpty() || txtApellidoP.getText().isEmpty()
                
                || txtApellidoMaterno.getText().isEmpty() || txtTelefono.getText().isEmpty()
                
                || txtCorreoElectronico.getText().isEmpty()) {

            btnEditarCliente.setVisible(true);
        }
        btnEditarCliente.setVisible(false);
    }

    private void llenarCampos(ClienteFrecuenteDTO cliente) {
        
        txtNombres.setText(cliente.getNombre());
        
        txtApellidoP.setText(cliente.getApellidoPaterno());
        
        txtApellidoMaterno.setText(cliente.getApellidoMaterno());
        
        txtTelefono.setText(cliente.getTelefono());
        
        txtCorreoElectronico.setText(cliente.getCorreo());
        
        txtFechaRegistro.setText(cliente.getFechaRegistro().toString());
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaFormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaFormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaFormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaFormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaFormularioCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditarCliente;
    private javax.swing.JButton btnGuardarCliente;
    private javax.swing.JButton btnLogo;
    private javax.swing.JLabel lblApellidoMaterno;
    private javax.swing.JLabel lblApellidoPaterno;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblFecharRegistro;
    private javax.swing.JLabel lblNombreBtnPantalla;
    private javax.swing.JLabel lblNombreRestaurante;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblPantalla;
    private javax.swing.JLabel lblPantallaActualNav;
    private javax.swing.JLabel lblTelefonod;
    private javax.swing.JPanel panMostrarNavegacion;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JPanel panSuperior;
    private javax.swing.JSeparator sep;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCorreoElectronico;
    private javax.swing.JTextField txtFechaRegistro;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
