package com.mycompany.restaurantepresentacion;

import com.mycompany.restaurantedtos.ClienteFrecuenteDTO;
import com.mycompany.utilerias.utilerias;
import javax.swing.SwingUtilities;

/**
 *
 * @author joset
 */
public class PantallaCliente extends javax.swing.JFrame {

    /**
     * Creates new form PantallaCliente
     */
    public PantallaCliente() {
        initComponents();
        //paneles reutilizables
        panelHeader = new com.mycompany.utilerias.PanelHeader();
        panelMenu = new com.mycompany.utilerias.PanelMenu();
        panelNavegacion = new com.mycompany.utilerias.PanelNavegacionPantallasPrincipales();

        panPrincipal.add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 130));
        panPrincipal.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 215, 640));
        panPrincipal.add(panelNavegacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 130, 1151, 45));

        panelNavegacion.setBreadcrumb("Clientes Frecuentes", "Menu");

        utilerias.estilizarBotonPrimario(btnEditarCliente);

        utilerias.estilizarBotonPrimario(btnNuevoCliente);

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        lblPrincipal1 = new javax.swing.JLabel();
        sep = new javax.swing.JSeparator();
        btnNuevoCliente = new javax.swing.JButton();
        btnEditarCliente = new javax.swing.JButton();
        panContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Clientes Menu");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panPrincipal.setMaximumSize(new java.awt.Dimension(1366, 768));
        panPrincipal.setPreferredSize(new java.awt.Dimension(1366, 768));
        panPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPrincipal1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        lblPrincipal1.setText("Clientes frecuentes");
        panPrincipal.add(lblPrincipal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        sep.setForeground(new java.awt.Color(18, 44, 79));
        panPrincipal.add(sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 1080, -1));

        btnNuevoCliente.setBackground(new java.awt.Color(18, 44, 79));
        btnNuevoCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNuevoCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoCliente.setText("Nuevo Cliente");
        btnNuevoCliente.setToolTipText("");
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });
        panPrincipal.add(btnNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 240, -1));

        btnEditarCliente.setBackground(new java.awt.Color(18, 44, 79));
        btnEditarCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarCliente.setText("Editar Cliente");
        btnEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClienteActionPerformed(evt);
            }
        });
        panPrincipal.add(btnEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 280, 230, -1));

        panContenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panContenidoLayout = new javax.swing.GroupLayout(panContenido);
        panContenido.setLayout(panContenidoLayout);
        panContenidoLayout.setHorizontalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );
        panContenidoLayout.setVerticalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        panPrincipal.add(panContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 177, 1150, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed

        Controlador.getIntancia().abrirFomularioCliente(this);
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void btnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteActionPerformed
        PantallaBusquedaClienteD dialogo = new PantallaBusquedaClienteD((java.awt.Frame) SwingUtilities.getWindowAncestor(this), true);
        dialogo.setVisible(true);

        ClienteFrecuenteDTO clienteElegido = dialogo.getClienteSeleccionado();

        if (clienteElegido != null) {
            Controlador.getIntancia().abrirFormularioEditarCliente(clienteElegido, this);
        }
    }//GEN-LAST:event_btnEditarClienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarCliente;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JLabel lblPrincipal1;
    private javax.swing.JPanel panContenido;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JSeparator sep;
    // End of variables declaration//GEN-END:variables
    private com.mycompany.utilerias.PanelHeader panelHeader;
    private com.mycompany.utilerias.PanelMenu panelMenu;
    private com.mycompany.utilerias.PanelNavegacionPantallasPrincipales panelNavegacion;
}
